import type { SkillDefinition } from './skills';

// These practices are deliberately organized by professional responsibility,
// not by file format, framework, language, database, or deployment vendor.
export const PROFESSIONAL_SKILL_DEFINITIONS: SkillDefinition[] = [
  {
    name: 'human-experience',
    description:
      'Coordinate evidence-based human, operator, and developer experience across every interactive medium.',
    domains: ['ux', 'design', 'human-factors'],
    kinds: ['ui'],
    instructions: `Treat experience as a cross-cutting product responsibility, not a synonym for frontend styling. Identify affected people, goals, context, capabilities, risks, existing behavior, and success criteria. Separate observation, stated requirements, assumptions, and aesthetic preference. Select only the relevant child practices and verify complete journeys including orientation, progress, interruption, failure, recovery, and return in the actual medium.`,
    should: ['design a professional user experience'],
    shouldNot: ['rename an internal variable'],
    evidence: [
      'Audience and context',
      'Selected disciplines and rationale',
      'Outcome evidence or explicit uncertainty',
    ],
  },
  {
    name: 'user-research',
    description:
      'Investigate users, operators, contexts, needs, and existing behavior before consequential decisions.',
    domains: ['ux', 'research'],
    parent: 'human-experience',
    activation: ['user research', 'customer interviews', 'field study', 'understand users'],
    instructions: `Define the decision and uncertainty first, then select observation, contextual inquiry, interviews, diary study, survey, or artifact analysis to fit it. Recruit across meaningful differences, protect privacy, separate observation from interpretation, seek contradictions, and never invent personas, quotes, prevalence, or consensus.`,
    should: ['research how operators perform this workflow'],
    shouldNot: ['apply an approved pixel adjustment'],
    evidence: [
      'Research question and method',
      'Evidence-source boundaries',
      'Observations and uncertainty',
    ],
  },
  {
    name: 'interaction-design',
    description:
      'Design behavior, controls, feedback, state transitions, recovery, and task flows for any medium.',
    domains: ['ux', 'interaction'],
    parent: 'human-experience',
    activation: ['interaction', 'workflow', 'task flow', 'controls', 'state transitions'],
    instructions: `Model goals, entry conditions, system state, actions, consequences, feedback, interruption, and recovery before arranging controls. Match behavior to confirmed input methods and risk. Specify initial, processing, partial, empty, invalid, blocked, success, failure, cancellation, undo, reconnection, and restoration states; verify with the real runtime or a faithful prototype.`,
    should: ['design the workflow for this native editor'],
    shouldNot: ['choose a brand color in isolation'],
    evidence: ['Task and state model', 'Input and feedback contract', 'Recovery verification'],
  },
  {
    name: 'information-architecture',
    description:
      'Organize concepts, navigation, labels, relationships, and findability across products, APIs, tools, and documents.',
    domains: ['ux', 'information-architecture'],
    parent: 'human-experience',
    activation: [
      'information architecture',
      'navigation structure',
      'taxonomy',
      'findability',
      'organize settings',
    ],
    instructions: `Inventory real content, objects, actions, relationships, terminology, lifecycle, and audience mental models. Organize by user goals and domain meaning, using facets when one tree distorts reality. Define grouping, labels, navigation, search, alternate entry, growth, permissions, and localization, then test representative findability tasks.`,
    should: ['reorganize this settings system'],
    shouldNot: ['normalize storage tables'],
    evidence: ['Concept inventory', 'Organization rationale', 'Findability results'],
  },
  {
    name: 'visual-interface-design',
    description:
      'Use composition, typography, color, density, imagery, and motion to communicate hierarchy and identity.',
    domains: ['ui', 'visual-design'],
    parent: 'human-experience',
    activation: ['visual design', 'visual polish', 'typography', 'layout', 'color system'],
    excludes: ['voice only'],
    instructions: `Confirm the visual medium, viewing conditions, platform conventions, content, product identity, and access constraints. Reuse existing tokens and components. Establish a purposeful hierarchy and design complete representative states. Reject ornamental gradients, glass, excessive cards, fake metrics, arbitrary shadows, and gratuitous motion; verify rendered output across scale, density, localization, contrast, and reduced motion.`,
    should: ['create a strong visual direction'],
    shouldNot: ['design a voice-only flow'],
    evidence: [
      'Purposeful visual direction',
      'Rendered state matrix',
      'Scale contrast and motion checks',
    ],
  },
  {
    name: 'content-error-design',
    description:
      'Design labels, instructions, status, errors, diagnostics, and recovery language that helps people act.',
    domains: ['ux', 'communication'],
    parent: 'human-experience',
    activation: [
      'content design',
      'error message',
      'microcopy',
      'status text',
      'diagnostics wording',
    ],
    instructions: `Identify the reader, decision, urgency, vocabulary, and next useful action. Cover orientation, progress, empty, partial, warning, permission, offline, failure, recovery, and completion states. Avoid blame, vague codes, cute distress language, and instructions that restate labels. Preserve actionable diagnostic context without exposing secrets and test comprehension, not grammar alone.`,
    should: ['make compiler diagnostics actionable'],
    shouldNot: ['optimize binary encoding'],
    evidence: ['Audience and action', 'Terminology review', 'Actionability evidence'],
  },
  {
    name: 'accessibility-practice',
    description:
      'Design equitable access across perception, operation, comprehension, environment, and assistive technology.',
    domains: ['accessibility', 'human-factors'],
    parent: 'human-experience',
    activation: [
      'accessibility',
      'assistive technology',
      'keyboard access',
      'screen reader',
      'reduced motion',
      'inclusive design',
    ],
    instructions: `Identify the actual medium, applicable standards, semantics, assistive technologies, input alternatives, environmental constraints, and cognitive or physical demands. Never depend on one sense, color, position, sound, fine motor action, memory, timing, or motion alone. Combine applicable automation with manual alternate-input and assistive-technology verification; do not force browser mechanics onto terminals, games, devices, APIs, or physical controls.`,
    should: ['audit accessibility of this product'],
    shouldNot: ['benchmark an internal allocator'],
    evidence: [
      'Applicable standard and surface',
      'Manual and automated results',
      'Untested combinations',
    ],
  },
  {
    name: 'usability-evaluation',
    description:
      'Evaluate whether representative people can understand, complete, recover from, and trust realistic tasks.',
    domains: ['ux', 'evaluation'],
    parent: 'human-experience',
    activation: ['usability test', 'evaluate ux', 'cognitive walkthrough', 'heuristic review'],
    instructions: `Define the decision, representative participants or justified proxies, realistic tasks, success measures, and severity model. Observe completion, errors, recovery, assistance, confidence, and comprehension without teaching the intended solution. Do not present convenience samples as population statistics; prioritize by harm and task criticality, preserve contradictions, and retest consequential changes.`,
    should: ['test whether people can complete onboarding'],
    shouldNot: ['run parser unit tests'],
    evidence: [
      'Method and participants',
      'Observable task results',
      'Severity and retest evidence',
    ],
  },
  {
    name: 'developer-experience',
    description:
      'Design APIs, SDKs, languages, tools, diagnostics, configuration, and workflows for reliable developer use.',
    domains: ['developer-experience', 'engineering'],
    parent: 'human-experience',
    activation: [
      'developer experience',
      'api usability',
      'sdk ergonomics',
      'tooling ux',
      'language ergonomics',
    ],
    instructions: `Treat APIs, configuration, diagnostics, commands, documentation, examples, observability, migration, and removal as one journey. Prefer coherent concepts, composable primitives, explicit state, inspectability, actionable failures, evidence-backed defaults, and escape hatches. Validate first use, repeat use, debugging, upgrade, rollback, and removal; never optimize solely for a short demo or fewer lines.`,
    should: ['design an ergonomic language API'],
    shouldNot: ['polish a consumer landing page'],
    evidence: ['Developer journey', 'Runnable examples', 'Failure migration and removal tests'],
  },

  {
    name: 'architecture-planning',
    description:
      'Plan boundaries, responsibilities, interfaces, qualities, and evolutionary constraints.',
    domains: ['planning', 'architecture'],
    parent: 'planning',
    activation: ['architecture plan', 'system design', 'component boundaries'],
    instructions: `Model responsibilities, data and control flow, trust boundaries, failure modes, quality attributes, and change axes. Compare alternatives against explicit criteria and record irreversible decisions and evolutionary seams. Prefer the least complex architecture satisfying demonstrated constraints.`,
    should: ['design the architecture'],
    shouldNot: ['schedule a release'],
    evidence: ['Boundary model', 'Tradeoffs', 'Quality scenarios'],
  },
  {
    name: 'migration-planning',
    description:
      'Plan compatible transitions between schemas, APIs, runtimes, architectures, or operational states.',
    domains: ['planning', 'migration'],
    parent: 'planning',
    activation: ['migration plan', 'upgrade path', 'data transition'],
    requires: ['verification'],
    instructions: `Inventory producers, consumers, state, compatibility, and recovery constraints. Define staged coexistence, translation or backfill, validation, cutover, rollback, and cleanup; make every phase safe to pause and test mixed versions.`,
    should: ['plan the schema migration'],
    shouldNot: ['build a greenfield component'],
    evidence: ['Compatibility matrix', 'Stage gates', 'Rollback plan'],
  },
  {
    name: 'release-planning',
    description: 'Plan evidence-gated delivery, rollout, observation, recovery, and support.',
    domains: ['planning', 'release'],
    parent: 'planning',
    activation: ['release plan', 'rollout plan', 'launch checklist'],
    requires: ['verification'],
    instructions: `Define release units, dependencies, user impact, telemetry, support ownership, preflight gates, rollout increments, observation windows, stop conditions, rollback, and post-release confirmation. Never equate a successful build with a successful release.`,
    should: ['plan the production rollout'],
    shouldNot: ['design internal architecture'],
    evidence: ['Release gates', 'Stop and rollback criteria', 'Post-release evidence'],
  },
  {
    name: 'feature-implementation',
    description:
      'Implement new end-to-end behavior through existing product and system boundaries.',
    domains: ['code', 'feature'],
    parent: 'implementation',
    activation: ['new feature', 'add support', 'implement capability'],
    requires: ['verification'],
    instructions: `Trace behavior from entry through state, side effects, outputs, errors, and feedback. Reuse established contracts and cover authorization, invalid input, partial failure, cancellation, persistence, and observability according to risk. Deliver a vertical slice, not disconnected scaffolding.`,
    should: ['add this capability'],
    shouldNot: ['restructure without behavior change'],
    evidence: ['End-to-end behavior', 'Failure coverage'],
  },
  {
    name: 'refactor-implementation',
    description: 'Improve internal structure while preserving defined external behavior.',
    domains: ['code', 'refactor'],
    parent: 'implementation',
    activation: ['refactor', 'restructure', 'extract abstraction', 'remove duplication'],
    requires: ['verification'],
    instructions: `Define invariants and compatibility first, add characterization evidence where behavior is uncertain, move in reviewable steps, reduce rather than relocate complexity, and remove obsolete paths without mixing unrelated features.`,
    should: ['refactor this subsystem'],
    shouldNot: ['add a user-visible feature'],
    evidence: ['Behavior invariants', 'Characterization checks'],
  },
  {
    name: 'integration-implementation',
    description:
      'Connect components or external systems through explicit contracts and failure boundaries.',
    domains: ['code', 'integration'],
    parent: 'implementation',
    activation: ['integrate', 'adapter', 'provider connection'],
    requires: ['verification'],
    instructions: `Confirm both sides, isolate translation, identity, lifecycle, retries, timeouts, cancellation, versioning, idempotency, and partial failure. Preserve provider-reported truth, keep unknown values unknown, and test drift and degraded dependencies.`,
    should: ['integrate this provider'],
    shouldNot: ['implement isolated internal logic'],
    evidence: ['Boundary contract', 'Failure and compatibility tests'],
  },
  {
    name: 'deterministic-debugging',
    description: 'Debug repeatable state, logic, parsing, lifecycle, or contract failures.',
    domains: ['debugging'],
    parent: 'debugging',
    activation: ['reproducible bug', 'wrong output', 'parse failure', 'state bug'],
    instructions: `Minimize input and path, inspect transitions and invariants, and locate the first incorrect value or decision rather than the final symptom.`,
    should: ['debug consistently wrong output'],
    shouldNot: ['race condition'],
    evidence: ['Minimal reproduction', 'First causal divergence'],
  },
  {
    name: 'concurrency-debugging',
    description: 'Debug races, deadlocks, ordering, cancellation, and shared-state failures.',
    domains: ['debugging', 'concurrency'],
    parent: 'debugging',
    activation: ['race condition', 'deadlock', 'threading bug', 'async ordering'],
    instructions: `Model actors, ownership, resources, synchronization, happens-before, cancellation, and teardown. Capture schedules or traces and repair the violated invariant; non-reproduction is not proof.`,
    should: ['debug a race condition'],
    shouldNot: ['repeatable pure function bug'],
    evidence: ['Concurrency timeline', 'Violated invariant', 'Stress regression'],
  },
  {
    name: 'distributed-debugging',
    description:
      'Debug failures spanning processes, services, nodes, clocks, or partial availability.',
    domains: ['debugging', 'distributed'],
    parent: 'debugging',
    activation: ['distributed failure', 'partial outage', 'message duplication', 'consistency bug'],
    instructions: `Correlate identities, versions, messages, retries, and transitions across boundaries. Account for delay, loss, duplication, reordering, partitions, and stale reads; reconstruct causality without trusting wall-clock order alone.`,
    should: ['debug cross-service inconsistency'],
    shouldNot: ['single-process failure'],
    evidence: ['Cross-boundary trace', 'Failure timeline', 'Recovery proof'],
  },
  {
    name: 'performance-debugging',
    description:
      'Debug latency, throughput, memory, energy, frame, or resource regressions using measurement.',
    domains: ['debugging', 'performance'],
    parent: 'debugging',
    activation: ['performance regression', 'memory leak', 'latency spike'],
    requires: ['performance-testing'],
    instructions: `Reproduce under a controlled representative workload, establish baseline and budget, then profile before optimizing. Separate startup, steady state, contention, saturation, allocation, I/O, and cleanup and verify equivalent builds with variance.`,
    should: ['debug a latency regression'],
    shouldNot: ['choose animation aesthetics'],
    evidence: ['Profile', 'Comparable benchmark', 'Resource accounting'],
  },
  {
    name: 'hardware-runtime-debugging',
    description:
      'Debug device, driver, graphics, accelerator, sensor, actuator, or runtime failures safely.',
    domains: ['debugging', 'device'],
    parent: 'debugging',
    activation: ['hardware bug', 'gpu crash', 'device failure', 'driver issue'],
    requires: ['simulation-device-testing'],
    instructions: `Record exact hardware, firmware, driver, runtime, workload, topology, and safety constraints. Separate host, runtime, driver, transport, and device hypotheses; use simulation and non-disruptive gates first and never claim physical proof from emulation.`,
    should: ['debug a GPU hang'],
    shouldNot: ['browser layout bug'],
    evidence: ['Environment identity', 'Layer localization', 'Safe proof'],
  },
  {
    name: 'functional-verification',
    description: 'Verify required behavior, contracts, boundaries, and regressions.',
    domains: ['verification'],
    parent: 'verification',
    activation: ['functional verification', 'acceptance test', 'regression check'],
    instructions: `Exercise representative success, boundary, invalid, failure, cancellation, persistence, and recovery paths. Verify observable effects rather than only internal calls.`,
    should: ['verify feature behavior'],
    shouldNot: ['visual preference review'],
    evidence: ['Acceptance results', 'Negative paths'],
  },
  {
    name: 'visual-verification',
    description:
      'Verify rendered hierarchy, states, resizing, density, and platform presentation in the real medium.',
    domains: ['verification', 'ui'],
    parent: 'verification',
    activation: ['visual verification', 'screenshot review', 'layout check'],
    requires: ['frontend-engineering'],
    instructions: `Inspect the real runtime at representative sizes, content, themes, inputs, and loading, empty, error, disabled, focus, and overflow states. Captures are evidence, not a substitute for behavior and semantics.`,
    should: ['visually verify the interface'],
    shouldNot: ['verify a headless parser'],
    evidence: ['Runtime captures', 'State and viewport matrix'],
  },
  {
    name: 'accessibility-verification',
    description: 'Verify equitable task completion with alternate inputs and assistive technology.',
    domains: ['verification', 'accessibility'],
    parent: 'verification',
    activation: ['accessibility audit', 'keyboard test', 'screen reader test'],
    requires: ['accessibility-practice'],
    instructions: `Combine applicable automation with alternate-input traversal, focus, semantics, names, relationships, contrast, scaling, motion, error recovery, and representative assistive technology. Automated success is never complete proof.`,
    should: ['audit accessibility'],
    shouldNot: ['benchmark throughput'],
    evidence: ['Manual task results', 'Automated findings', 'Residual limitations'],
  },
  {
    name: 'reliability-verification',
    description: 'Verify resilience, degradation, restart, recovery, and sustained operation.',
    domains: ['verification', 'reliability'],
    parent: 'verification',
    activation: ['reliability test', 'fault recovery', 'soak test', 'resilience'],
    instructions: `Inject realistic faults and resource pressure; test restart, replay, timeout, cancellation, partial availability, durability, cleanup, recovery objectives, and health observability.`,
    should: ['verify outage recovery'],
    shouldNot: ['check typography'],
    evidence: ['Fault matrix', 'Recovery timing', 'Sustained-run artifacts'],
  },
  {
    name: 'security-verification',
    description: 'Verify enforced security properties at trust and authorization boundaries.',
    domains: ['verification', 'security'],
    parent: 'verification',
    activation: ['security verification', 'authorization test', 'isolation test'],
    requires: ['security-review'],
    instructions: `Test identities, roles, denied paths, isolation, secret exposure, injection, unsafe defaults, auditability, and fail-closed behavior at the enforcing layer. Prompt wording and hidden UI are not enforcement.`,
    should: ['verify authorization boundaries'],
    shouldNot: ['format code'],
    evidence: ['Positive and negative authorization evidence', 'Boundary proof'],
  },
  {
    name: 'performance-verification',
    description:
      'Verify performance claims against representative budgets and reproducible measurements.',
    domains: ['verification', 'performance'],
    parent: 'verification',
    activation: ['verify performance', 'performance gate', 'latency budget'],
    requires: ['performance-testing'],
    instructions: `Define workloads, environment, budgets, warmup, sampling, variance, and comparison rules. Verify relevant cold, warm, steady, peak, degraded, and cleanup behavior and report distributions and resource costs.`,
    should: ['verify the latency target'],
    shouldNot: ['debug an unmeasured slowdown'],
    evidence: ['Measurements', 'Budget comparison', 'Variance'],
  },
  {
    name: 'technical-communication',
    description:
      'Explain technical systems, decisions, operations, and evidence to technical readers.',
    domains: ['documents', 'technical'],
    parent: 'documents-communication',
    activation: ['technical document', 'design document', 'engineering report'],
    instructions: `State scope, constraints, mechanism, decisions, alternatives, interfaces, risks, evidence, and unresolved work. Use visuals only when they clarify relationships and keep examples executable or explicitly illustrative.`,
    should: ['write a technical design'],
    shouldNot: ['write an executive brief'],
    evidence: ['Technical review', 'Traceable claims'],
  },
  {
    name: 'executive-communication',
    description:
      'Present decision-relevant outcomes, tradeoffs, risk, cost, and asks without hiding uncertainty.',
    domains: ['documents', 'executive'],
    parent: 'documents-communication',
    activation: ['executive brief', 'leadership update', 'decision memo'],
    instructions: `Lead with the decision, status, or outcome and tie evidence to impact, options, risk, timing, ownership, and explicit asks. Include implementation detail only when it changes the decision.`,
    should: ['write a leadership brief'],
    shouldNot: ['write an API reference'],
    evidence: ['Decision clarity', 'Risk and ask completeness'],
  },
  {
    name: 'instructional-communication',
    description: 'Teach a reader to complete and verify a task safely.',
    domains: ['documents', 'instructional'],
    parent: 'documents-communication',
    activation: ['tutorial', 'how-to guide', 'setup guide', 'runbook', 'onboarding'],
    instructions: `Define prerequisites, starting state, goal, actions, decisions, expected feedback, failure recovery, warnings, and completion checks. Test from the intended environment without omitted expert knowledge.`,
    should: ['write a setup guide'],
    shouldNot: ['write an executive strategy'],
    evidence: ['Walkthrough result', 'Recovery and completion checks'],
  },
  {
    name: 'reference-communication',
    description: 'Create precise, searchable, version-aware factual references.',
    domains: ['documents', 'reference'],
    parent: 'documents-communication',
    activation: ['reference documentation', 'api reference', 'configuration reference'],
    instructions: `Organize around stable concepts and lookup paths. Define names, types, units, defaults, constraints, lifecycle, compatibility, errors, examples, and version scope; derive from authoritative definitions and test examples where possible.`,
    should: ['write an API reference'],
    shouldNot: ['write a narrative tutorial'],
    evidence: ['Source comparison', 'Example validation', 'Coverage review'],
  },
  {
    name: 'application-security',
    description:
      'Assess application trust and authorization boundaries without assuming web architecture.',
    domains: ['security', 'application'],
    parent: 'security-review',
    activation: [
      'application security',
      'authorization review',
      'input validation',
      'session security',
    ],
    instructions: `Map assets, actors, entry points, privilege changes, and abuse cases. Trace authentication, authorization, validation, serialization, secrets, isolation, disclosure, and state through enforced runtime paths. Select controls for the actual medium and demonstrate reachable findings and fail-closed behavior.`,
    should: ['review this application authorization boundary'],
    shouldNot: ['audit a dependency lockfile'],
    evidence: ['Threat map', 'Enforcement-path evidence', 'Negative tests'],
  },
  {
    name: 'infrastructure-security',
    description:
      'Assess hosts, networks, identities, deployments, and operational control planes in their actual environment.',
    domains: ['security', 'infrastructure'],
    parent: 'security-review',
    activation: [
      'infrastructure security',
      'host hardening',
      'network policy',
      'deployment security',
    ],
    instructions: `Inventory compute, identity, network, storage, deployment, observability, backup, and administration before recommending controls. Evaluate least privilege, segmentation, provenance, secrets, patching, logging, recovery, and break-glass paths without assuming cloud, containers, Kubernetes, Linux, or internet exposure.`,
    should: ['review host and network hardening'],
    shouldNot: ['review a form validator'],
    evidence: ['Environment inventory', 'Effective configuration', 'Recovery proof'],
  },
  {
    name: 'authorization-security',
    description:
      'Design and verify subject-resource-action authorization policy at the actual enforcement boundary.',
    domains: ['security', 'authorization'],
    parent: 'application-security',
    activation: [
      'authorization security',
      'authorization review',
      'access control',
      'permission boundary',
      'role policy',
    ],
    instructions: `Inventory subjects, resources, actions, ownership, delegation, tenancy, inheritance, revocation, and administrative escape paths. Define policy independently from UI visibility, enforce it at every reachable boundary, default unknown cases closed, and test positive, negative, cross-tenant, stale-session, confused-deputy, and revocation behavior.`,
    should: ['verify this access control policy'],
    shouldNot: ['review host firewall rules'],
    evidence: ['Authorization matrix', 'Enforcement trace', 'Negative and revocation tests'],
  },
  {
    name: 'supply-chain-security',
    description:
      'Evaluate provenance and compromise risk across source, dependencies, tools, builds, artifacts, and updates.',
    domains: ['security', 'supply-chain'],
    parent: 'security-review',
    activation: [
      'supply chain security',
      'dependency audit',
      'build provenance',
      'artifact signing',
    ],
    instructions: `Trace source and contributors through dependencies, build tools, CI, artifacts, distribution, installation, and update. Identify mutable or unauthenticated steps, implicit trust, concentration, generated-code opacity, and credential exposure. Verify integrity using mechanisms supported by the actual ecosystem.`,
    should: ['audit dependency and build provenance'],
    shouldNot: ['analyze consent language'],
    evidence: ['Provenance map', 'Dependency inventory', 'Artifact verification'],
  },
  {
    name: 'privacy-engineering',
    description:
      'Minimize and govern sensitive information across collection, use, retention, sharing, and deletion.',
    domains: ['security', 'privacy', 'data'],
    parent: 'security-review',
    activation: ['privacy', 'privacy review', 'personal data', 'data retention', 'consent design'],
    instructions: `Map subjects, purposes, fields, sensitivity, collection, transformations, storage, access, sharing, retention, deletion, and inferences. Challenge necessity, verify lifecycle and controls, and separate engineering findings from jurisdiction-specific legal conclusions.`,
    should: ['review personal-data handling'],
    shouldNot: ['benchmark throughput'],
    evidence: ['Data lifecycle map', 'Necessity rationale', 'Access and deletion verification'],
  },
  {
    name: 'embedded-device-security',
    description: 'Assess device, firmware, physical, communication, update, and safety boundaries.',
    domains: ['security', 'embedded'],
    parent: 'security-review',
    activation: ['embedded security', 'firmware security', 'device threat model', 'secure boot'],
    instructions: `Establish physical access, debug interfaces, boot chain, provenance, keys, communications, peripherals, update, recovery, limits, and safety consequences. Verify safe failure, rollback resistance, authenticated updates, isolation, and recovery on representative hardware or bounded simulation.`,
    should: ['threat model device firmware'],
    shouldNot: ['audit website cookies'],
    evidence: ['Attack surface', 'Boot and update evidence', 'Physical versus simulated boundary'],
  },
  {
    name: 'language-runtime-security',
    description:
      'Assess compilers, interpreters, runtimes, loaders, sandboxes, and foreign interfaces.',
    domains: ['security', 'runtime'],
    parent: 'security-review',
    activation: [
      'runtime security',
      'compiler security',
      'runtime sandbox',
      'custom language runtime',
      'sandbox escape',
      'memory safety',
    ],
    instructions: `Define claimed guarantees and trace parsing, lowering, optimization, execution, allocation, concurrency, loading, capabilities, native interfaces, and untrusted code. Seek semantic mismatches, undefined behavior, confused authority, verifier gaps, unsafe representations, and exhaustion; never infer safety from language branding.`,
    should: ['review a custom runtime sandbox'],
    shouldNot: ['review cloud IAM'],
    evidence: ['Guarantee model', 'Adversarial reproducer', 'Cross-layer trace'],
  },
  {
    name: 'exploratory-data-analysis',
    description:
      'Understand unfamiliar data through structure, quality, distributions, relationships, and anomalies.',
    domains: ['data', 'analysis'],
    parent: 'data-analysis',
    activation: ['exploratory analysis', 'explore dataset', 'find patterns', 'data profiling'],
    instructions: `Identify provenance, observation unit, schema, units, missingness, censoring, duplication, selection, time coverage, and transformations. Examine distributions, subgroups, relationships, anomalies, and cleaning sensitivity while labeling discoveries as hypotheses. Use the native medium; do not assume SQL, Python, or tables.`,
    should: ['explore this unfamiliar dataset'],
    shouldNot: ['prove a causal effect'],
    evidence: ['Quality profile', 'Reproducible transformations', 'Exploratory findings'],
  },
  {
    name: 'statistical-inference',
    description:
      'Estimate effects or relationships with explicit population, assumptions, uncertainty, and multiplicity.',
    domains: ['data', 'statistics'],
    parent: 'data-analysis',
    activation: [
      'statistical analysis',
      'confidence interval',
      'hypothesis test',
      'estimate effect',
    ],
    instructions: `Define estimand, population, sampling or assignment, assumptions, confounders, dependence, missingness, and decision consequence before choosing a method. Report effect size, uncertainty, sensitivity, multiplicity, units, and practical significance; distinguish association, prediction, and causation.`,
    should: ['estimate this effect with uncertainty'],
    shouldNot: ['make an exploratory dashboard'],
    evidence: [
      'Estimand and assumptions',
      'Uncertainty and sensitivity',
      'Reproducible calculation',
    ],
  },
  {
    name: 'experimental-analysis',
    description:
      'Design and analyze controlled or quasi-experimental evidence around a predeclared decision.',
    domains: ['data', 'experiment'],
    parent: 'data-analysis',
    activation: ['experiment design', 'a/b test', 'causal analysis', 'randomized trial'],
    instructions: `State the causal question, units, intervention, comparator, outcomes, assignment, interference, stopping, exclusions, and analysis before outcomes where possible. Justify power and meaningful effect; for observational designs expose identification assumptions and falsification checks.`,
    should: ['design an A/B experiment'],
    shouldNot: ['summarize descriptive trends'],
    evidence: ['Predeclared design', 'Assignment evidence', 'Power and sensitivity'],
  },
  {
    name: 'operational-data-analysis',
    description:
      'Turn production or process data into decisions while accounting for instrumentation and system change.',
    domains: ['data', 'operations'],
    parent: 'data-analysis',
    activation: [
      'operational analysis',
      'production metrics',
      'incident data',
      'process monitoring',
    ],
    instructions: `Start from the operational decision. Validate metric definitions, event generation, clocks, sampling, aggregation, retries, identity, late data, schema changes, and observability gaps. Compare meaningful baselines and segments and tie findings to thresholds and verification.`,
    should: ['analyze production reliability metrics'],
    shouldNot: ['review academic literature'],
    evidence: ['Metric lineage', 'Baseline rationale', 'Decision-linked findings'],
  },
  {
    name: 'data-visualization',
    description:
      'Design accurate visual representations matched to the analytical question, audience, and display medium.',
    domains: ['data', 'visualization'],
    parent: 'data-analysis',
    activation: ['data visualization', 'design a chart', 'dashboard design', 'visualize results'],
    instructions: `Identify the comparison, distribution, relationship, composition, geography, flow, or uncertainty before choosing an encoding. Preserve scale, units, denominator, uncertainty, and missingness; use a table for exact lookup and never add charts decoratively.`,
    should: ['choose a chart for these results'],
    shouldNot: ['style application navigation'],
    evidence: ['Encoding rationale', 'Scale and access review', 'Reader task verification'],
  },
  {
    name: 'ml-evaluation',
    description:
      'Evaluate predictive or generative systems against representative tasks, failure costs, uncertainty, and drift.',
    domains: ['data', 'machine-learning'],
    parent: 'data-analysis',
    activation: ['model evaluation', 'ml benchmark', 'classifier evaluation', 'llm evaluation'],
    instructions: `Define deployment tasks, populations, failures, costs, baselines, and thresholds before metrics. Prevent leakage and contamination; stratify meaningful conditions and report uncertainty, calibration, robustness, abstention, and justified adversarial cases. Use blinded rubrics and agreement checks for human judgment.`,
    should: ['design a blinded LLM benchmark'],
    shouldNot: ['benchmark server latency only'],
    evidence: ['Evaluation protocol', 'Baseline and slices', 'Failure analysis'],
  },
  {
    name: 'factual-research',
    description:
      'Resolve concrete factual questions using authoritative current evidence and explicit uncertainty.',
    domains: ['research', 'facts'],
    parent: 'research',
    activation: [
      'fact check',
      'verify current information',
      'research the current',
      'authoritative source',
    ],
    instructions: `Decompose checkable claims, identify time sensitivity, prefer primary authority, verify dates, triangulate consequential claims, and record provenance. Distinguish fact, synthesis, and inference; search ranking is not source quality.`,
    should: ['fact-check this current claim'],
    shouldNot: ['interview users'],
    evidence: ['Claim-source trace', 'Recency and authority', 'Inference boundaries'],
  },
  {
    name: 'literature-research',
    description:
      'Synthesize scholarly or technical literature by question, evidence quality, disagreement, and applicability.',
    domains: ['research', 'literature'],
    parent: 'research',
    activation: ['literature review', 'research papers', 'state of the art', 'systematic review'],
    instructions: `Frame scope, inclusion, disciplines, dates, and evidence hierarchy. Search beyond one vocabulary, assess methods and external validity, and synthesize agreement, conflict, gaps, and applicability rather than listing papers. Distinguish peer review, preprint, benchmark, opinion, and replication.`,
    should: ['review research on agent routing'],
    shouldNot: ['compare product pricing'],
    evidence: ['Search rationale', 'Quality assessment', 'Synthesis and gaps'],
  },
  {
    name: 'market-competitive-research',
    description:
      'Assess markets and alternatives through customer, product, business, and adoption evidence.',
    domains: ['research', 'market'],
    parent: 'research',
    activation: [
      'market research',
      'competitive analysis',
      'competitor research',
      'product landscape',
    ],
    instructions: `Define the customer decision and dimensions before collecting users, jobs, substitutes, capability, constraints, pricing, distribution, adoption, switching costs, and differentiation evidence. Prefer direct observation and primary documentation; separate facts from inferred strategy and never equate feature count or popularity with quality.`,
    should: ['compare competing agent harnesses'],
    shouldNot: ['review statistical literature'],
    evidence: ['Dimensioned comparison', 'Provenance', 'Inference uncertainty'],
  },
  {
    name: 'repository-research',
    description:
      'Answer architectural and behavioral questions by tracing the actual repository, history, configuration, and runtime.',
    domains: ['research', 'repository'],
    parent: 'research',
    activation: [
      'research repository',
      'understand codebase',
      'trace implementation',
      'architecture investigation',
    ],
    instructions: `Trace declarations to callers, configuration, generated artifacts, tests, runtime adapters, persistence, and visible behavior. Treat comments as claims until corroborated and distinguish implemented, configured, tested, and merely planned behavior.`,
    should: ['trace the live prompt path'],
    shouldNot: ['survey commercial competitors'],
    evidence: [
      'File and symbol trace',
      'Runtime corroboration',
      'Implemented versus documented distinction',
    ],
  },
];
