/**
 * Progressive-disclosure content for the human-experience branch. These
 * playbooks are intentionally independent of a rendering stack or delivery
 * medium; the resolver decides when their parent skill is relevant.
 */
export type ExperienceSkillName =
  | 'human-experience'
  | 'user-research'
  | 'interaction-design'
  | 'information-architecture'
  | 'visual-interface-design'
  | 'content-error-design'
  | 'accessibility-practice'
  | 'usability-evaluation'
  | 'developer-experience';

export interface ExperienceSkillPlaybook {
  title: string;
  content: string;
}

export const EXPERIENCE_SKILL_PLAYBOOKS: Record<ExperienceSkillName, ExperienceSkillPlaybook> = {
  'human-experience': {
    title: 'Human experience practice',
    content: `Start by naming the people affected, their goals, operating context, capabilities, stakes, and the actual medium. “User” is rarely one audience: distinguish primary operators, occasional users, administrators, support staff, developers, bystanders, and people affected by an automated decision. Inspect existing behavior before proposing a replacement. Record what is observed, what was requested, what is inferred, and what remains unknown.

Frame the work as a journey rather than a screen or endpoint. Map entry, orientation, setup, ordinary use, progress, handoff, interruption, degraded operation, failure, recovery, return, and exit. Identify the few moments where misunderstanding, delay, irreversible action, exclusion, or loss of trust would be expensive. Choose child practices because of the decision at hand: research for uncertainty about people or context; interaction design for behavior; information architecture for findability; visual design for hierarchy; content for comprehension; accessibility for equitable operation; evaluation for evidence.

Make experience requirements testable. State the task, conditions, success signal, recovery expectation, and evidence source. Use the confirmed input, output, and runtime constraints of the product; do not translate every problem into browser UI. A command-line tool, voice flow, device, game, API, and document can each have a human experience.

Reject attractive but unsupported redesigns, invented personas, isolated happy paths, visual polish that conceals ambiguity, and claims that a design is intuitive without observing use. Deliver a concise decision record, selected disciplines and rationale, journey/state coverage, and explicit uncertainty. Verify the consequential journey in the real runtime or a faithful prototype, then report both what worked and what was not tested.

Run the work as an evidence loop. First, write a one-sentence outcome and a boundary statement naming what the experience work may change and what it must preserve. Second, build an evidence ledger with four columns: source, observation, confidence, and decision affected. Third, model the current journey before proposing the target journey. Fourth, select the smallest intervention that resolves the highest-cost break. Fifth, exercise it under ordinary and adverse conditions. Finally, compare observed results with the original outcome and record whether to ship, revise, investigate, or stop. Do not jump from a request such as “make it easier” to controls or layouts without turning “easier” into observable behavior.

Use a decision matrix for each important moment. Rows are user and system states; columns are available action, expected result, feedback, recovery, access path, and evidence. At minimum include new and returning people, permitted and unpermitted roles, valid and invalid input, connected and disconnected operation, sufficient and constrained resources, synchronous and interrupted execution, and success and failure. Mark impossible combinations explicitly instead of silently omitting them. When states multiply, prioritize combinations by likelihood, harm, irreversibility, and uncertainty, while preserving every safety-critical case.

Maintain a claim ledger. “People need this” requires research evidence; “this control is discoverable” requires evaluation; “this state is accessible” requires relevant manual and automated checks; “this flow is faster” requires comparable measurement; “the system recovers” requires an exercised recovery path. Replace unsupported superlatives with bounded statements. Aesthetic confidence is not behavioral evidence, internal approval is not user validation, and a successful render is not proof that a task works.

Apply accessibility from framing through verification. Include people who use alternative input, magnification, captions or transcripts, simplified language, reduced motion, high contrast, or support assistance where relevant. Account for fatigue, stress, divided attention, noisy or bright environments, intermittent connectivity, and limited hardware. If direct participation is unavailable, use platform guidance and specialist inspection as provisional evidence and label the gap. Never turn accessibility into a final checklist owned by one child discipline.

When requirements conflict, state the trade rather than averaging it away. Safety and truthful system state outrank visual neatness. Preventing irreversible harm outranks minimizing one extra step. Expert efficiency may justify shortcuts only when a safe default, visible state, and recovery route remain. Privacy may constrain personalization or telemetry. Offline resilience may constrain freshness. Record the chosen priority, affected groups, rejected alternative, and evidence needed to revisit it.

Recover deliberately from weak inputs. If the brief is vague, inspect the product and produce a provisional outcome with assumptions. If evidence conflicts, preserve segments and contexts rather than manufacturing consensus. If the requested experience promises capability the runtime lacks, expose the boundary and redesign the promise. If a prototype cannot faithfully represent latency, permissions, persistence, hardware, or assistive behavior, use it only for the claims it can support. If testing reveals a critical failure, stop polishing adjacent details, repair the contract, and repeat the consequential task.

Before handoff, require a trace from each major decision to a user or operational need and from each important requirement to a verification result. Confirm that another agent can identify the audience, intended outcome, state model, constraints, unresolved risks, and next check without guessing. Remove placeholder copy, fabricated data, decorative controls, unreachable recovery actions, and interactions that exist only to make the artifact look complete. The final report should distinguish implemented behavior, evaluated behavior, inferred benefit, deferred work, and unknowns.

Govern cross-channel consistency when the journey spans people, automation, documentation, notifications, support, or physical environments. The same operation must retain its identity, consequence, and status across surfaces even when presentation differs. Record where a handoff changes ownership, authority, latency, privacy, or recoverability. Verify that delayed messages cannot contradict current state and that support guidance does not promise an action unavailable in the product. When one channel is inaccessible or unavailable, provide a truthful alternate route that preserves the essential outcome rather than a dead-end referral. Include abandonment and re-entry: people must know what persisted, expired, or requires renewed consent.`,
  },
  'user-research': {
    title: 'User research practice',
    content: `Begin with a decision that research could change. Write the uncertainty, the affected groups, the consequence of being wrong, and the minimum evidence needed. Choose a method that fits the question: contextual observation for actual practice, interviews for language and rationale, diary methods for longitudinal work, surveys for bounded descriptive questions, artifact or support-log analysis for existing behavior, and prototype sessions for prospective choices. Do not use a survey to substitute for observing complex work.

Recruit for meaningful variation in role, experience, access needs, environment, geography, organization, incentives, and risk. Convenience participants and internal colleagues can be useful proxies only when labelled as such. Prepare neutral prompts, realistic tasks, consent and recording boundaries, and a plan for sensitive data. During sessions, ask people to show their normal work; do not teach the intended path, defend a design, treat pauses as agreement, or convert one vivid comment into a general rule.

Separate raw observations, participant interpretations, researcher inferences, and recommendations. Look deliberately for contradictions and disconfirming cases. Synthesize by behavior, need, context, barrier, and confidence—not demographic stereotype. Quote sparingly and accurately; never fabricate quotes, personas, prevalence, or consensus. Preserve unknowns and explain where evidence cannot generalize.

Turn findings into decisions with traceable links: finding, implication, proposed change, risk, and validation needed. A useful output includes method and sample boundaries, task evidence, themes with counterexamples, prioritized opportunities, and open questions. Validate consequential decisions with a second method or follow-up observation when feasible. Research is complete when it reduces the stated uncertainty enough to make a responsible decision, not when a slide deck looks persuasive.

Write a research contract before recruitment. Include the decision owner, decision deadline, hypotheses or open questions, participant criteria, exclusion criteria, method, session count rationale, stopping rule, incentives, consent model, data retention, and analysis plan. Phrase hypotheses so evidence can weaken them. Define what would cause the team to keep the current design, change direction, seek another sample, or decline to decide. If no plausible result could alter the decision, do not perform ceremonial research.

Build a sampling matrix rather than a fictional representative user. Rows should capture roles and meaningful contexts; columns should capture experience, frequency, access needs, environment, incentives, risk exposure, and relevant technology. Recruit across the cells that could change the answer. Do not report percentages from qualitative samples as population estimates. For quantitative claims, define the population, sampling frame, response bias, missing data, uncertainty, and analysis before collecting responses. Treat support tickets, analytics, and sales notes as behaviorally useful but selection-biased evidence.

Pilot every protocol. Check that tasks can be completed with available accounts, data, devices, permissions, and time; that prompts do not reveal the answer; that sensitive material can be safely skipped; and that recording captures the needed evidence. Prepare branch prompts for silence, confusion, off-topic answers, disclosure of private information, and technical failure. During the session, distinguish a comprehension probe such as “What do you expect?” from leading instruction such as “Open settings.” Record timestamps and artifacts where consent allows so synthesis does not depend on memory.

Use a structured evidence table after each session: task, observed action, participant words, contextual condition, outcome, researcher interpretation, alternative explanation, and confidence. Keep verbatim evidence separate from normalized notes. Include successful behavior and workarounds, not only failures. Look for cases that contradict early themes, and have a second reviewer challenge high-impact interpretations when feasible. Do not infer motivation from behavior alone or behavior from stated preference alone.

Choose the method with an explicit decision rule. Use observation when the gap between reported and actual practice matters. Use interviews for mental models, vocabulary, history, and rationale. Use diary or longitudinal logging for episodic behavior and change over time. Use concept or prototype evaluation for comprehension and predicted consequence, while noting that intention in a session does not establish adoption. Use a survey only for questions respondents can reliably self-report. Use experiments when causal attribution and assignment conditions are defensible. Combine methods when their failure modes complement each other.

Protect participants and product truth. Collect the least sensitive data needed; separate contact details from research records; redact credentials, customer data, health data, and identifying artifacts; honor withdrawal; and document retention and deletion. Do not recruit people through coercive managerial relationships without safeguards. Do not disguise research as support or vice versa. For vulnerable populations or high-stakes domains, obtain appropriate specialist or ethics review rather than improvising.

When sessions fail, recover without laundering the evidence. A broken prototype can still reveal expectation before the break, but cannot support a task-completion claim. A proxy participant may expose obvious terminology problems but not establish target-audience fit. Low recruitment requires narrowing the claim or changing the method, not inflating weak observations. Translation or facilitation differences must be included as context. If saturation is claimed, name the theme and the absence of new evidence; do not treat a fixed session count as automatic saturation.

Synthesis should produce a finding only when it names the evidence, affected context, confidence, and decision relevance. Rank opportunities using severity of unmet need, reach within the bounded sample, strategic importance, feasibility, and cost of delay; keep those factors visible instead of collapsing them into unexplained priority labels. For every recommendation, name the behavioral mechanism and a follow-up test. End with a readout that includes limits and counterevidence before recommendations, plus a repository of sanitized notes that another reviewer can audit.`,
  },
  'interaction-design': {
    title: 'Interaction design practice',
    content: `Design behavior before arranging controls. Define the user goal, entry conditions, permissions, relevant system state, available actions, constraints, consequences, and exit conditions. Model state transitions explicitly, especially where data changes, automation acts, cost is incurred, or a person can lose work. Confirm actual inputs and outputs first: pointer, touch, keyboard, controller, voice, command line, hardware control, assistive technology, asynchronous event, or API client each need different interaction contracts.

For every consequential flow, specify initial, empty, loading or processing, partial, unavailable, invalid, blocked, success, failure, cancellation, interruption, reconnection, restoration, and undo or correction states. Make feedback timely, proportional, understandable, and tied to the action that caused it. Prevent errors when practical; when prevention conflicts with expert speed, expose a safe escape hatch. Make destructive or irreversible actions legible before commitment and offer recovery that matches the real system capability—never promise undo that does not exist.

Use progressive disclosure to reduce unnecessary decisions without hiding vital state. Keep action labels tied to outcomes rather than implementation. Do not use a confirmation dialog as the default answer to unclear interaction design, nor rely on hover, color, timing, or a single gesture as the only path.

Verify with a real runtime or a faithful prototype using representative tasks and interruption cases. Inspect whether people can predict results, recognize state, correct mistakes, and resume work. Deliver a task/state model, input and feedback contract, recovery rules, and evidence from the tested flows. Call out unverified edge states instead of treating the happy path as completion.

Create an interaction contract before implementation. For each action specify who may invoke it, prerequisites, input channels, visible affordance or discoverability route, system command, latency expectation, optimistic or confirmed behavior, resulting state, feedback channel, cancellation point, idempotency, and recovery. Define ownership when multiple people or agents can act at once. If the runtime cannot distinguish “accepted,” “started,” and “completed,” do not collapse them into a single reassuring success state.

Use a state-transition table for consequential objects. Rows name current state and triggering event; columns name guards, next state, side effects, feedback, persistence, and reversal. Include duplicate activation, stale data, timeout, partial success, permission loss, conflicting edits, process termination, device rotation or resize, and returning after absence where relevant. Illegal transitions should fail closed with actionable feedback. For long operations, expose whether work continues after the interface closes and how status can be recovered later.

Decide interaction patterns from constraints, not habit. Direct manipulation suits visible, reversible spatial changes; a command suits precise repeatable expert work; a wizard suits a bounded sequence with meaningful dependencies; staged disclosure suits optional complexity; inline editing suits low-risk local changes; review-and-commit suits costly or cross-cutting changes. Confirmation is warranted when consequence is surprising and difficult to reverse, not merely because an action is important. Typed phrases and repeated prompts are not substitutes for permission design and undo.

Specify focus and orientation independent of device. On visual keyboard surfaces, define logical traversal, focus entry and return, focus after insertion or deletion, escape behavior, and visible focus. On voice, audio, terminal, controller, or hardware surfaces, provide equivalent location, selection, cancellation, and status cues. Ensure targets tolerate tremor and coarse input; repeated actions do not require precision; timeouts can be extended where safe; and gestures, sound, or vibration have alternatives. Never trap input in a component or steal focus for non-urgent updates.

Design concurrency and interruption explicitly. Show when information is stale, when another actor owns a lock, when local work is unsaved, and what merging will preserve or discard. Autosave must reveal failure and last-known persistence rather than creating false confidence. Resuming should restore task context, not merely reopen the starting point. For destructive batches, preview scope and exceptions, support safe cancellation, and report per-item outcomes when atomic completion is unavailable.

Test with an action-state matrix. Exercise every primary action in allowed, disallowed, pending, successful, failed, repeated, cancelled, and interrupted conditions. Add alternative input and reduced-motion passes, long content, slow processing, and loss of connectivity or dependency. Observe whether the person can state what will happen before acting, tell what is happening during action, verify what happened afterward, and repair the result. Capture system logs alongside interface evidence when the visible result could lie.

Common failure patterns require root fixes: a disabled action without explanation needs eligibility guidance; an endless spinner needs timeout and recovery semantics; duplicate submission needs idempotency or guarded state; a disappearing error needs persistent contextual status; unexpected navigation needs preservation of work and orientation; a modal chain needs a clearer task model; and hidden expert gestures need discoverable alternatives. Do not solve uncertain state with animation or solve runtime inconsistency with softer language.

Handoff artifacts must let implementation and verification agree. Provide the transition model, action contract, representative sequences, timing assumptions, copy, accessibility behavior, observability hooks, and acceptance cases. Mark which behavior is mandated, which is a design option, and which depends on unresolved system capability. Review the implemented runtime against these artifacts and update whichever is wrong; do not leave design specifications as fictional truth.

Instrument interaction only when measurement is authorized and useful. Define the event, state, actor boundary, privacy class, and question it answers; avoid collecting raw content or identifiers by default. Analytics may reveal that an action occurred, but not that it was understood or intended. Validate event emission for success, failure, cancellation, and repeated actions so telemetry does not turn partial attempts into completed tasks.`,
  },
  'information-architecture': {
    title: 'Information architecture practice',
    content: `Treat information architecture as a model of a domain, not decoration for a navigation bar. Inventory real objects, content, actions, relationships, lifecycle states, terminology, permissions, audiences, and volumes. Observe the terms people use and the routes they take today. Separate a product’s internal storage model from the concepts people must find and understand; a database-normalized structure is not automatically a usable one.

Organize around meaningful tasks and domain relationships. Use a hierarchy only where one primary home is truthful; use facets, cross-links, search, saved views, contextual actions, or alternate entry points when people approach the same thing differently. Define labels that are specific, stable, and distinguishable. Avoid organization by team ownership, implementation detail, clever metaphors, and ambiguous buckets such as “Other” when a clearer concept exists.

Specify navigation, orientation, local context, search behavior, filtering, sorting, empty results, permissions, deep links, history, migration, growth, localization, and offline or degraded constraints as applicable to the medium. A terminal command hierarchy, API resource model, settings surface, documentation set, and physical control panel can all require architecture. Do not assume global navigation or search is available or appropriate.

Test findability with representative tasks and realistic wording: where would someone start, what label would they choose, how would they recover from a wrong route, and can they recognize the destination? Measure observable success and confusion rather than voting on a sitemap. Deliver a concept inventory, relationship model, organization rationale, labels and alternate paths, plus findability results and known growth risks.

Begin with a content-and-object audit. For each item record canonical name, synonyms, description, owner, audience, source of truth, lifecycle, sensitivity, permission model, volume, update rate, relationships, and existing access routes. Identify duplicates that are truly the same concept and homonyms that only look the same. Do not merge concepts to simplify a diagram when their permissions, lifecycle, or meaning differ. Mark absent but expected content separately from empty content.

Create a relationship model before a hierarchy. Express containment, membership, reference, dependency, sequence, version, ownership, and inheritance explicitly. State cardinality and whether relationships can change. Then choose organization schemes—task, topic, object, chronology, geography, audience, lifecycle, or frequency—based on observed retrieval needs. A primary hierarchy may coexist with facets and links; do not force every object into exactly one branch when the domain is networked.

Use a routing matrix for important tasks. Rows are representative intents expressed in user language; columns are likely starting context, cue or label sought, route, alternate route, permission outcome, zero-result behavior, and recovery from a wrong turn. Include direct links, external entry, recent-history return, notifications, automation, and support instructions where applicable. Ensure a person arriving deep in the structure can identify location, object state, and next meaningful actions without returning to a home surface.

Treat search as an information system, not a box. Define indexed objects and fields, vocabulary normalization, misspellings, aliases, ranking signals, filters, scopes, privacy, stale content, and no-result recovery. Distinguish “no matching items,” “not searched due to permissions,” “index unavailable,” and “filter excludes results” without leaking existence of protected objects. Offer suggestions grounded in available data rather than invented matches. For command or API discovery, help, completion, and error suggestions serve equivalent roles.

Plan evolution. Define naming and location changes, redirects or aliases, saved link behavior, API or command compatibility, bookmarks and saved views, migration of user-created organization, deprecation messaging, and removal criteria. Test the architecture against projected volume and new object types. Avoid a generic overflow bucket as the permanent growth strategy. Ownership changes must not strand content or make previously valid routes silently misleading.

Evaluate with more than preference. Run open or closed sorting only when the question matches those techniques; sorting cannot validate workflows, permissions, or cross-links by itself. Use first-choice tasks, structure testing, search-log analysis, support evidence, and realistic end-to-end retrieval. Record success, path, backtracking, time where meaningful, confidence, wrong-destination recognition, and recovery. Segment results by role and familiarity when those change the vocabulary.

Accessibility and language are architectural constraints. Labels must remain distinguishable when read out of visual context. Heading or grouping levels must communicate genuine structure. Repeated labels need contextual names. Navigation order should follow conceptual order across alternative input. Localization may change alphabetic ordering, label length, grammatical form, search tokenization, and cultural categories; do not freeze an English-centric taxonomy into identifiers without review.

When evidence conflicts, preserve alternate routes rather than seeking one universal menu. When internal stakeholders demand organization by department, compare it with task evidence and expose the cost. When permissions create apparent gaps, design explanation without revealing protected information. When migration cannot preserve every deep link, inventory impacted routes and provide explicit fallbacks. Handoff the model in implementation-readable terms where possible, and verify real labels, locations or commands, permissions, search, and growth cases after implementation.

Define governance for user-created structure. Specify who may create, rename, move, merge, archive, share, or delete containers, tags, aliases, and saved views; how conflicts are resolved; and what happens to dependent links and automation. Distinguish personal organization from shared canonical structure so one person’s convenience cannot silently rewrite another person’s model. Provide auditability and restoration for consequential taxonomy changes, and test imported or legacy structures that violate current naming rules. Document canonical identifiers separately from mutable display labels so renaming does not corrupt references.`,
  },
  'visual-interface-design': {
    title: 'Visual interface design practice',
    content: `First confirm that a visual interface is part of the task and learn its viewing conditions: device or surface, scale, distance, lighting, density, platform conventions, content variability, identity constraints, access needs, and motion capability. Inspect the existing design language, reusable tokens, assets, and complete screens before inventing new ones. State a concise visual read before implementation: product or page kind, audience, character, evidence for a design-system or native direction, and intended variance, motion, and density. If two directions would materially change the result, ask one focused question; otherwise make the decision visible and proceed. A visual direction should clarify purpose, priority, relationship, state, and trust; it is not an excuse to apply a fashionable style.

Build a hierarchy from content and task importance. Establish type roles, spacing rhythm, alignment, grouping, contrast, color meaning, imagery policy, elevation or boundaries, and responsive or resizable behavior appropriate to the medium. Use a small, coherent set of visual signals repeatedly. Reserve emphasis for meaningful differences: current state, risk, primary action, status, and error. Choose variation deliberately: do not default to a centered hero, equal card grid, purple glow, glass effect, generic dashboard, or inherited trendy palette merely because it is familiar to a model. A pattern is acceptable when it serves the established direction, platform convention, content, or task—not because a ban list says it is never allowed. Test representative complete states, not a pristine empty mockup: long and localized text, sparse and dense data, selected and disabled controls, errors, progress, empty results, and degraded conditions.

Use color, shape, text, placement, and semantics together so that no single visual cue carries essential meaning. Keep color, type, iconography, spacing, borders, elevation, and radius coherent across the whole surface. Respect contrast, text scaling, reduced motion, and platform requirements. Motion should explain state, preserve orientation, or provide feedback; every animation needs a reason and a reduced-motion behavior. Do not manufacture dashboards, people, activity, testimonials, or metrics to make a design look alive.

Run a visual pre-flight before declaring completion. Check that the implemented hierarchy matches the visual read; the layout is not accidentally repetitive; primary actions and states remain distinct; assets and imagery are purposeful; the palette and token system remain coherent; copy is real and readable; motion is justified; and dense, empty, failure, localized, keyboard-focus, and reduced-motion states remain usable. These are universal checks, not web prescriptions. Apply confirmed-medium checks separately: browser reflow and semantics for web; platform scaling, shortcuts, and window behavior for native; plain-text, color-off, and automation behavior for terminal; attention, comfort, and frame budget for game/spatial; and physical controls, legibility, safe state, and resource constraints for embedded. Verify in the actual medium at relevant sizes and environments. Deliver the visual read, rationale, component/token changes, representative state matrix, claim-by-claim pre-flight result, and unresolved compromises rather than claiming polish from screenshots alone.

Create a visual brief that can be disproved. Record the primary task, viewing context, highest-priority content, intended emotional register, platform or physical conventions, brand evidence, required states, content extremes, and prohibited misrepresentations. Collect references for specific properties—type rhythm, information density, material, motion, icon language, or spatial composition—rather than asking to copy an unrelated product’s surface. Separate direct evidence from interpretation. If no identity system exists, establish a small reversible direction instead of fabricating a full brand.

Inventory the existing system before adding tokens or components. For each type style, color, spacing increment, radius, border, elevation, icon, illustration, and motion pattern, record usage and semantic purpose. Consolidate only when values serve the same purpose; visual similarity alone is not semantic equivalence. Prefer semantic tokens such as surface, elevated surface, critical text, focus indicator, and selected state over palette-position names in consuming components. Define fallback behavior for monochrome, high contrast, printing, low-color devices, or unavailable assets where the medium requires it.

Build a hierarchy map for each representative surface. Rank regions and objects by task importance, urgency, frequency, and consequence. Then assign visual variables deliberately: position and grouping establish relationships; type size and weight establish reading order; contrast establishes emphasis; space establishes separation; and motion establishes transition or causality. Avoid using every variable at once. If five elements all appear primary, the hierarchy has failed. If secondary information disappears under realistic contrast, distance, or density, reducing emphasis has become concealment.

Use a component-state matrix. Rows are components or visual objects; columns include rest, hover when supported, focus or equivalent orientation, pressed, selected, mixed, disabled, unavailable, loading, success, warning, error, stale, and permission-restricted. Add content variants: no label, long label, multiline value, large number, unknown value, missing asset, localization expansion, right-to-left text, and user-generated content. A state may be inapplicable, but it must be intentionally marked rather than forgotten. Ensure state distinctions remain without color and at the intended distance or scale.

Typography is an interface system. Define roles by purpose and hierarchy, supported weights, minimum sizes, line lengths, line heights, numeral behavior, code or data treatment, fallback fonts, script coverage, and scaling. Test font loading failure and platform substitution. Do not shrink critical labels to preserve a composition. Truncation must expose a reliable path to the full value and must not erase the distinguishing part of identifiers. For dashboards, terminals, instruments, or spatial displays, verify tabular alignment and distance legibility rather than importing editorial typography rules blindly.

Color requires a semantic and environmental contract. For each semantic color, define foreground and background pairs, interaction states, high-contrast equivalent, non-color cue, and meaning across themes. Evaluate contrast using applicable standards and real rendering, while also checking glare, dim conditions, projector washout, color-vision variation, and display limitations as relevant. Do not derive error, success, warning, and brand solely by tinting one hue. Never let decorative imagery reduce critical legibility or make generated content look like verified product data.

Iconography and imagery need provenance and interpretation checks. Use an icon only when its meaning is conventional in context or paired with a label. Keep stroke, optical size, alignment, fill, and active-state behavior coherent. Provide accessible names based on function, not appearance. Verify licenses and attribution requirements for assets. Avoid stock imagery that invents customers, facilities, devices, or outcomes. Generated imagery must be labelled and reviewed for false text, impossible hardware, exclusionary representation, and misleading evidence.

Define layout behavior through constraints, not isolated pixel coordinates. Specify fixed, intrinsic, proportional, wrapping, scrolling, clipping, and priority behavior for each region. Test minimum and maximum supported sizes, zoom or scaling, split views, safe areas, orientation changes, text expansion, overlays, virtual keyboards, and multiple windows where applicable. On fixed hardware, test viewing angle, reach, occlusion, gloves, vibration, and environmental light. On spatial or game surfaces, protect comfort, horizon or camera stability, readable depth, attention budget, and frame time.

Motion has an initiation, duration, interruption, completion, and fallback contract. State which event triggers it, what relationship it explains, whether input remains available, where focus or selection ends, what happens when repeated, and how reduced-motion mode behaves. Avoid motion that delays access to information, repeatedly captures attention, implies progress without work, or moves critical targets. Test dropped frames and interrupted transitions; the final state must remain correct even when animation is skipped.

Use comparison checkpoints during implementation. Capture the current build at representative states and compare it with the visual brief, existing system, and selected target. Inspect hierarchy before micro-details, then spacing and alignment, typography, color and state, imagery, and motion. Fix causes in tokens, constraints, or shared components when the defect repeats. Do not compensate for a weak layout with shadows, gradients, ornamental cards, excessive dividers, or arbitrary animation. Do not apply global normalization when a deliberate exception communicates meaning.

Visual verification must include perception and operation. View at intended distance and density, blur or squint to inspect hierarchy, remove color to inspect redundant cues, enlarge text, enable high contrast and reduced motion, navigate with alternative input, and exercise live updates. Compare screenshots or captures where useful, but also inspect focus, timing, clipping, hit targets, assistive output, and runtime performance. A static reference cannot prove those properties. Record exact sizes, themes, devices or simulators, content fixtures, and untested environments.

When visual and functional requirements conflict, preserve readable state and task completion. When brand colors fail contrast, adjust the application or pairing and document the exception. When localized content breaks composition, reflow rather than abbreviate meaning without language review. When performance cannot support an effect, remove or simplify it. When existing components are inconsistent, avoid a one-off new style; either repair the shared rule within scope or clearly isolate the provisional exception with follow-up.

Handoff a visual decision record, token and component deltas, asset manifest, layout constraints, state matrix, motion contract, accessibility results, and representative captures. Every capture must identify whether it is a target, implementation, or proposal. Separate exact requirements from illustrative examples. Remove unused tokens, placeholder assets, fake metrics, duplicate component variants, and unexplained magic values. Another implementer should be able to reproduce the behavior without guessing which pixels were accidental.

Audit visual attention as a limited resource. Inventory everything that flashes, animates, pulses, badges, changes color, raises contrast, plays media, or remains fixed above other content. Rank each signal by urgency and expiration, then remove competition that delays recognition of the highest-priority state. Notifications must decay or clear according to real status; stale urgency erodes trust. In monitoring, vehicle, game, medical, industrial, or other attention-sensitive contexts, verify recognition under divided attention and realistic distance without manufacturing dangerous test conditions.

For data-rich visuals, preserve the underlying quantities and uncertainty. Choose tables, charts, diagrams, maps, spatial encodings, or plain values according to the comparison or lookup task. Label units, time ranges, missing values, transforms, aggregation, sampling, and freshness. Avoid truncated axes, decorative area encodings, false precision, hidden denominators, and palettes that imply categories or order absent from the data. Provide an accessible textual or tabular equivalent that supports the essential decision, not a generic summary. Test sparse, dense, negative, extreme, tied, and unavailable values.

Review theming as a matrix rather than inverting colors. Check every semantic surface and state across supported themes, system contrast modes, transparency settings, wallpapers or camera backgrounds, and display technologies. Images, shadows, overlays, disabled states, charts, syntax colors, selection, and focus often fail independently of ordinary text. Theme changes during operation must not lose state or trigger disorienting motion. Persist preferences only within the product’s privacy and platform conventions.

Where customization is allowed, define guardrails and reset. Establish which tokens or assets people may change, preview consequences in representative states, validate legibility and format, preserve an undoable prior configuration, and explain propagation across shared surfaces. User control does not excuse shipping an unusable combination silently; warn or block only according to documented severity and authority. Distinguish personal preference from organization-wide identity so an individual experiment cannot unexpectedly affect everyone.`,
  },
  'content-error-design': {
    title: 'Content and error design practice',
    content: `Write for a decision and an action. Identify who is reading, what they are trying to do, what they already know, what happened, urgency, risk, vocabulary, and the next useful step. Use the terminology people encounter in the domain, not internal object names or vague product slogans. Keep labels concrete and outcomes visible; a person should not need to activate a control to learn its consequence.

Design language as a complete state system: orientation, instructions, unavailable capability, empty result, in-progress work, partial completion, warning, confirmation, permission request, offline or degraded operation, failure, recovery, and success. For an error, explain what failed in plain terms, the impact, what can be done now, and any identifier or diagnostic detail needed for support—without exposing secrets, private data, or unsafe implementation detail. Pair a useful action with the message when a real action exists; do not use “try again” as a substitute for diagnosis.

Avoid blame, false reassurance, cute language during distress, unexplained codes, passive ambiguity, all-caps urgency, and instructions that merely repeat nearby labels. Do not hide a serious error behind a toast that disappears before it can be read. Preserve accurate uncertainty: “may not have saved” is better than claiming a save failed or succeeded without evidence.

Review content in the real context, including constrained surfaces, localization expansion, assistive output, and interrupted work. Test comprehension with representative readers or a justified proxy; grammar approval alone is not validation. Deliver a state/content inventory, terminology decisions, recovery copy, diagnostic privacy review, and evidence of whether people understood the required action.

Build a terminology ledger before polishing sentences. Record each domain concept, preferred term, prohibited or ambiguous alternatives, audience-specific explanation, grammatical form, localization note, and source of truth. Use the same term for the same thing unless the audience genuinely requires translation between mental models. Do not rename a concept merely to avoid repetition. Preserve distinctions such as remove versus delete, stop versus pause, local versus synced, submitted versus approved, and unavailable versus unauthorized.

Write from a state-content matrix. Rows name moments in the journey; columns name trigger, audience, known facts, unknown facts, required action, tone, persistence, announcement channel, diagnostic detail, and recovery. Include first use, empty, loading, long-running, partial, stale, validation failure, permission denial, dependency failure, offline, conflict, cancellation, completion, and irreversible outcome. If the system cannot know the cause, say what is observable and provide safe next checks rather than guessing.

Use a four-part error contract for consequential failures: identify the affected object or action, state the confirmed outcome, explain the safest next step, and provide a trace or support path when useful. Preserve entered work whenever possible and say whether it remains available. Distinguish retryable from terminal failure. A retry action must be idempotent or warn about duplicate effects. If resolution requires another role, name the role and what information can safely be shared.

Match urgency to consequence. Reserve interruptive presentation and urgent language for conditions requiring immediate attention. Warnings belong before commitment when they can change a decision; errors belong next to the affected action or value; background status should remain discoverable without repeatedly interrupting work. Success messages should confirm consequential results, not celebrate routine navigation. Never use friendly tone to minimize loss, blame a person for system constraints, or imply that support can recover data when that is unknown.

Write controls as outcome-bearing phrases appropriate to the medium. Distinguish “Save draft,” “Publish,” and “Submit for review.” Pair unfamiliar icons, commands, gestures, or hardware markings with discoverable explanations. Instructions should describe prerequisites and consequences, not narrate obvious mechanics. For voice and assistive output, avoid strings that depend on punctuation, capitalization, spatial position, or emoji for meaning. For terminal and logs, keep human explanation separable from stable machine-readable codes.

Review security and privacy line by line. Never place secrets, raw tokens, private content, internal paths, stack traces, or protected object existence in broadly visible messages. Also avoid becoming so vague that recovery is impossible. Use a safe public message plus a correlation identifier and restricted diagnostics when needed. Permission denial must not reveal resources the reader is not authorized to know about. Confirmation copy must accurately name the scope of data sharing, retention, billing, or external action.

Test comprehension with task questions: what happened, what was affected, what happens next, what action is available, and what risk remains? Ask readers to paraphrase rather than rate clarity. Include hurried readers, novices, domain experts, relevant language backgrounds, and people using assistive output where feasible. Test copy with real dynamic values, localization expansion, pluralization, dates, currencies, identifiers, and missing fields. A grammatically correct message that produces the wrong action has failed.

When constraints are severe, prioritize identity, state, consequence, and action. Progressive disclosure may move diagnostics to details or logs, but must not hide essential recovery. If content conflicts with actual behavior, repair the contract or state the limitation; do not write around it. Handoff the ledger, state matrix, message catalog, localization notes, privacy decisions, and tested comprehension results. Mark provisional copy and ownership so placeholders do not silently ship.

Version consequential content with the behavior it describes. When commands, permissions, prices, retention, limits, or recovery capability change, identify every message and document derived from that contract and retest them together. Do not let cached notifications, old translations, support macros, or release notes contradict current operation. If multiple product versions remain supported, make applicability visible without asking the reader to infer it from wording. Define expiry or review ownership for time-sensitive guidance.`,
  },
  'accessibility-practice': {
    title: 'Accessibility practice',
    content: `Start with the actual product surface and its applicable obligations, standards, and user environments. Accessibility is not a browser-only checklist: inspect the semantics, alternatives, interaction model, hardware, operating system services, documentation, command interface, device constraints, and support workflow that people really use. Identify perceptual, motor, cognitive, speech, language, environmental, and temporary-access constraints relevant to the task, without assuming a single “average” user.

Make each critical task perceivable, understandable, operable, and robust through more than one channel where needed. Do not require color, position, sound, fine motor precision, memorization, strict timing, motion, or one input method as the only way to succeed. Preserve programmatic meaning and state when the medium supports assistive technologies. Ensure focus or equivalent orientation, input feedback, errors, time limits, media alternatives, zoom or scale, and motion behavior match the platform rather than imposing web mechanics on every system.

Use automated checks to catch repeatable defects, but treat a clean scanner as a narrow signal. Manually exercise representative workflows with alternative input and relevant assistive technology or platform services. Include realistic content, validation errors, dynamic updates, dense states, and recovery—not just a static home screen. When specialist testing is unavailable, state the limit and avoid claiming conformance.

Prioritize barriers by task criticality, frequency, harm, and availability of workaround. Fix root semantics and interaction contracts before cosmetic patches. Deliver the applicable standard and scope, test matrix, issues with reproduction and impact, remediations, retest evidence, and untested combinations. Never claim universal accessibility or compliance beyond the evidence.

Start with an accessibility scope statement. Name the product versions, surfaces, platforms, languages, tasks, standards or regulations, assistive configurations, and environments covered. Distinguish legal conformance review, standards audit, inclusive design work, and usability with disabled participants; they provide different evidence. Identify critical tasks such as authentication, consent, payment, safety response, content creation, recovery, and support, then protect their complete journeys before optimizing isolated components.

Build a barrier matrix. Rows are critical task steps; columns are vision, hearing, motor, speech, cognition, language, seizure or vestibular risk, environmental constraint, and assistive-technology compatibility. For each cell record demand, barrier, alternative, severity, evidence, and owner. Include permanent, temporary, and situational constraints without reducing people to diagnoses. Mark untested combinations. Prioritize any barrier that blocks completion, causes loss, hides state, prevents recovery, or requires disclosure of disability to obtain ordinary access.

Define an input-and-output contract for each task. Inputs may include keyboard, switch, pointer, touch, voice, controller, command, API automation, or physical control. Outputs may include text, semantics, speech, sound, vibration, light, shape, position, or logs. Essential information needs an equivalent that preserves timing and meaning, not merely a decorative alternative. Do not require simultaneous actions, path-based gestures, rapid repetition, precise drag, or speech when a simpler alternative is feasible.

For semantic surfaces, verify names, roles, values, states, relationships, reading order, headings, groups, live updates, validation, and focus management. Prefer native platform semantics or well-tested shared controls. If a custom control is necessary, implement its complete interaction and announcement contract, including disabled and invalid states. A visually hidden label that is wrong is not accessible. An element in an accessibility tree that cannot be operated is not accessible. Do not duplicate announcements or force people through decorative content.

For non-semantic or constrained media, identify equivalent orientation and control mechanisms. Terminal output should work without color, preserve readable ordering, separate machine output, and offer stable help. Games and spatial systems need remappable input, subtitle and caption controls, motion and camera options, readable overlays, pause behavior, and alternatives for timed precision where compatible with the product purpose. Hardware needs tactile or shape differentiation, reachable controls, safe physical feedback, and instructions available through an accessible channel.

Test content and perception under real variation: text scaling, zoom, high contrast, forced colors or system themes, color-vision differences, dark and bright environments, low bandwidth, missing media, captions, transcripts, language expansion, and cognitive load. Check that reflow or scaling does not lose content, context, or action. Avoid disabling platform accessibility settings. Time limits require warning, extension, or a documented safety reason. Flashing, parallax, auto-motion, and haptics require applicable risk controls and user preferences.

Run manual task scripts with representative alternative input. Begin from launch or entry, not a conveniently prepared state. Exercise setup, normal action, validation error, dynamic update, interruption, destructive confirmation, and recovery. Record exact platform, assistive technology, versions, settings, input device, and outcome. Automated rules can supplement this matrix but cannot validate reading order intent, meaningful labels, cognitive clarity, caption quality, physical reach, or recovery.

Treat defects as contract failures. A missing name may reveal a component API that permits unlabeled controls; repair the API or shared component when possible. Lost focus after deletion requires a deterministic focus destination. Unannounced saving requires a status mechanism with controlled verbosity. Inaccessible drag requires an equivalent move operation. Low contrast caused by arbitrary values requires semantic tokens. Do not scatter local attributes or exceptions while leaving the reusable cause intact.

When a standard cannot be met, document the exact criterion or requirement, affected task and people, technical or product reason, attempted alternatives, interim accommodation, owner, and deadline. Do not call a workaround equivalent when it adds dependency, delay, cost, or disclosure. Provide an accessible support path, but never use support as the default substitute for product access. High-risk exceptions need explicit accountable acceptance, not an agent’s silent judgment.

Handoff an auditable result: scope, applicable requirements, barrier matrix, automated output with false positives resolved, manual scripts, assistive-technology evidence, participant evidence if available, defect severity, remediation, regression coverage, and residual risk. Report conformance only to the tested standard and scope. “No issues found” means no issues were found in specified checks; it does not mean everyone can use the product.`,
  },
  'usability-evaluation': {
    title: 'Usability evaluation practice',
    content: `Define the decision before choosing an evaluation method. State the representative audience or justified proxy, realistic tasks, environment, success criteria, measures, and what result would change the plan. Use moderated task sessions when behavior and reasoning matter, a cognitive walkthrough when knowledgeable inspection is appropriate, heuristic review for structured expert critique, telemetry or support evidence for deployed behavior, and comparative studies only when the alternatives and measures are genuinely comparable.

Write tasks in the participant’s goal language, with enough context to be realistic but without disclosing the intended path. Observe completion, time or effort where meaningful, errors, recovery, assistance, comprehension, confidence, and trust. Do not coach someone through the design, turn every hesitation into a defect, or treat a convenience sample as population statistics. Record the conditions under which findings apply; a noisy field setting, assistive technology, novice user, and expert administrator can reveal different failures.

Synthesize evidence into distinct findings with task, observation, likely cause, scope, confidence, severity, and suggested next validation. Prioritize by harm, irreversibility, frequency, task criticality, and availability of workaround—not by which criticism sounds strongest. Preserve contradictory observations and separate observed problems from hypotheses about causes.

Retest consequential changes using the same task conditions where possible. A useful report names participants or proxy limits, method, tasks, raw outcome summary, severity rationale, changes made, and retest result. Avoid declaring an interface “usable,” “intuitive,” or statistically representative when the evidence only supports a narrower conclusion.

Write an evaluation protocol that another facilitator could repeat. Include product build, entry state, accounts and data, equipment, environment, audience criteria, sample rationale, task order, counterbalancing when needed, session timing, prompts, assistance policy, stopping conditions, measures, consent, recording, and data handling. Pilot it with at least a justified proxy to catch impossible tasks, leaked answers, broken fixtures, and unrealistic timing. Freeze consequential protocol changes after sessions begin or report them as separate conditions.

Use a task-outcome matrix. Rows are participants or evaluation passes; columns are task completion, critical error, noncritical error, assistance, backtracking, time when valid, expectation before action, confidence after action, recovery, and notable context. Define success before observing sessions. Distinguish completion with the intended mechanism, completion through a valid alternative, and accidental completion. Do not average away a safety-critical failure or compare times when task conditions differ.

Facilitation must protect evidence. Use neutral probes such as “What are you looking for?” and “What do you expect to happen?” Allow silence. If assistance is necessary, record its exact level and continue the task as assisted rather than successful. Do not teach the design between tasks unless the protocol studies learning. Separate participant distress or privacy concerns from product friction and stop when consent or safety requires it.

Select inspection methods honestly. A cognitive walkthrough examines whether an appropriate person can form the goal, notice an action, associate it with the goal, and understand feedback at each step. A heuristic review applies named principles consistently and still requires evidence from the product. An accessibility audit addresses specific access requirements. Analytics reveal aggregate events only to the fidelity of instrumentation. Support records overrepresent people who could and chose to ask for help. None alone substitutes for observing representative task performance.

Assign severity with explicit factors: task impact, harm, persistence, frequency within observed conditions, affected audience, workaround quality, and recoverability. Keep confidence separate from severity; a potentially catastrophic issue may be high severity with low confidence and require urgent validation. Group repeated symptoms only when evidence supports a shared cause. Preserve isolated but consequential findings rather than discarding them because they occurred once.

Protect accessibility and inclusion in the protocol. Recruit relevant access needs when the task decision affects them, provide accommodations without changing the core goal, allow preferred assistive technology, and record the configuration. Ensure materials, consent, scheduling, incentives, and remote tools are accessible. If only non-disabled proxies were used, do not infer disabled-user outcomes. Evaluate language, fatigue, attention, motor demand, and environmental conditions when those shape performance.

Recover from compromised evidence visibly. If a build fails, retain only observations gathered before the failure that remain interpretable. If instrumentation is wrong, correct it and restart measurement rather than estimating. If a facilitator led a participant, mark the task assisted. If recruitment misses a critical segment, narrow the conclusion. If design changes occur mid-study, version results. Never repair a report by silently excluding inconvenient sessions or converting qualitative impressions into invented metrics.

After remediation, rerun the failed tasks plus adjacent regressions. Verify that the fix removes the cause without increasing effort, hiding capability, or creating a new barrier. Compare equivalent conditions and report differences as observations, not causal proof unless the design supports it. Deliver the protocol, anonymized outcome matrix, evidence clips or references, findings with severity and confidence, decision mapping, remediation, retest, and limits. A finding is closed only when the relevant task passes or an accountable decision accepts the residual risk.

Preserve reproducibility after the study. Store sanitized fixtures, build identifiers, task scripts, scoring definitions, and analysis decisions where authorized. Document exclusions and missing observations. A later evaluator should be able to distinguish a changed product from changed conditions or changed scoring. Retain only data permitted by consent and policy; reproducibility never justifies keeping unnecessary participant data.`,
  },
  'developer-experience': {
    title: 'Developer experience practice',
    content: `Treat developer experience as the complete journey of a person integrating, operating, debugging, changing, upgrading, and removing a technical product. Identify their roles, existing knowledge, runtime constraints, security boundaries, language or protocol conventions, and failure costs. Inspect the actual interface—API, SDK, command, configuration, language feature, build tool, documentation, examples, logs, and migration path—before optimizing a local snippet.

Design around coherent domain concepts and composable primitives. Make states, ownership, lifecycle, side effects, concurrency, limits, and failure behavior explicit. Defaults should be evidence-backed, safe for the common case, inspectable, and reversible where possible; an escape hatch should be deliberate, documented, and not silently undermine safety. Prefer predictable naming and behavior over clever brevity. Keep configuration discoverable and validate it near the source of the mistake.

Design diagnostics as part of the interface: identify the failed operation, relevant location or resource, likely cause when justified, safe corrective action, and diagnostic context without leaking secrets. Supply runnable, maintained examples that show setup, ordinary use, failure handling, teardown, and version assumptions. Avoid examples that hide essential permissions, dependencies, cleanup, or production constraints.

Evaluate first use, repeat use, debugging, upgrade, rollback, and removal with representative developers or a faithful clean-environment exercise. Measure whether someone can form a correct mental model, complete a realistic task, find an answer, and recover from a mistake. Deliver a journey map, interface contract, examples and diagnostics review, compatibility and migration plan, plus evidence and known friction. Do not equate fewer lines or a fast demo with ergonomic design.

Begin with a developer-task contract. Name the actor, starting knowledge, supported environment, permissions, existing project state, intended outcome, latency or resource constraints, safety boundary, and observable success. Inventory every touchpoint needed to finish: discovery, installation, authentication, configuration, first operation, composition, test, deployment or distribution, monitoring, debugging, update, rollback, data export, and removal. Do not optimize the first five minutes while leaving failure and lifecycle work opaque.

Model the interface in domain terms. For each resource or operation define identity, ownership, lifetime, mutability, consistency, ordering, concurrency, authorization, limits, billing or resource effect, error classes, idempotency, cancellation, and observability. Separate the stable contract from convenience wrappers. Make implicit ambient state—current directory, environment variables, credentials, network, daemon, cache, or selected account—inspectable. Avoid behavior that changes silently by invocation context unless that context is an explicit part of the contract.

Use a workflow matrix across novice, returning, expert, administrator, automation, and support roles. Rows are lifecycle tasks; columns are prerequisite discovery, shortest safe path, advanced path, expected output, failure signal, recovery, documentation location, and verification. A quick start may optimize novice success, while reference documentation protects precision and automation. Do not force experts through tutorials or ask novices to assemble a contract from reference fragments.

Design installation and setup as reversible state changes. Declare supported versions and platforms, dependency provenance, filesystem or system modifications, network access, credential storage, services started, ports used, and cleanup. Detect conflicts before mutation. Provide dry-run or preview for risky setup where feasible. Uninstall must identify retained user data and credentials rather than claiming total removal. Never instruct broad destructive cleanup as routine troubleshooting.

Authentication and authorization deserve first-class diagnostics without secret exposure. Distinguish missing credentials, invalid credentials, expired credentials, insufficient scope, wrong account, unavailable identity provider, and network failure. Show which profile or principal is active through safe identifiers. Never treat browser, CLI, OAuth, and API-key identities as interchangeable unless the provider contract establishes that. Examples must use placeholders and least privilege, and logs must redact secrets by construction.

Define an error taxonomy. Each stable error class should identify category, retryability, affected operation or resource, safe human action, programmatic representation, and diagnostic correlation. Preserve causal chains for debugging while keeping ordinary output concise. Exit status, exceptions, result types, protocol status, and structured logs must agree. Avoid parsing human prose as the only automation contract. Rate limits and partial success need exact scope and retry guidance; a generic “something went wrong” transfers system uncertainty to the developer.

Examples are executable specifications. Test them from clean environments with declared versions. Show the smallest complete ordinary path, then validation failure, transient failure, cancellation or cleanup, and production boundary. Do not omit imports, permissions, initialization, awaits, disposal, escaping, or error handling to make snippets look elegant. Keep generated and copied identifiers visibly synthetic. Link examples to the contract version and fail verification when they drift.

Documentation needs an information architecture: outcome-oriented tutorials, task-oriented how-to guidance, explanatory mental models, exact reference, troubleshooting, security, limits, compatibility, and migration. Search using the language emitted by real errors. Cross-link concepts at decision points without duplicating divergent truth. Mark version and applicability. If behavior is experimental or unsupported, say so where it is selected, not only in release notes.

Plan compatibility before change. Classify source, binary, behavior, protocol, schema, configuration, data, and operational compatibility as relevant. State deprecation start, replacement, detection, warning channel, migration tooling, rollback, and removal condition. Test upgrades from supported prior states using realistic data and plugins or integrations. A build that compiles after upgrade does not prove behavioral compatibility. Never silently reinterpret configuration or discard unknown fields without a deliberate contract.

Exercise clean-room journeys. Use an environment without maintainer caches, credentials, undocumented services, or source-tree shortcuts. Capture commands or actions, outputs, elapsed steps, deviations from docs, failures, and recovery. Repeat with invalid input, offline or unavailable dependency, permission denial, version mismatch, interrupted operation, and rollback. Include alternative input and readable structured output where human tools are involved. Record what requires external infrastructure and what was simulated.

Evaluate the mental model, not merely completion. Ask the developer to predict side effects, explain ownership and lifetime, locate limits, distinguish local from remote state, diagnose a planted failure, and describe rollback. A copied command that happens to work can conceal a broken model. Measure time only for comparable conditions; also record assistance, documentation hops, error recovery, and unsafe assumptions. Internal framework authors are useful expert reviewers but not substitutes for target integrators.

When tests expose friction, fix the earliest misleading contract. Repeated configuration mistakes may require schema and diagnostics, not more prose. Cleanup failures may require ownership APIs. Excessive boilerplate may reveal missing composition primitives, but hiding essential lifecycle in magic is worse. If the runtime cannot guarantee a promised behavior, narrow the promise and expose status. If backward compatibility blocks a clean design, offer an explicit versioned path and migration rather than ambiguous dual semantics.

Handoff a verified journey ledger, interface and error contracts, environment matrix, executable examples, documentation map, telemetry or observability plan, security review, compatibility policy, migration and rollback evidence, and known limits. Distinguish supported from tested environments and tested from merely documented behavior. Remove stale snippets, fake endpoints, hidden setup assumptions, undocumented flags, and diagnostics that expose secrets. Another developer should be able to reproduce the evidence without access to the author’s machine or memory.`,
  },
};
