/** Luna-authored delivery playbooks. Proposal data only; not wired into runtime. */
const CORE_DELIVERY_PLAYBOOKS = {
  planning: `Establish outcome, stakeholders, constraints, authority, current evidence, and done conditions. Separate facts, assumptions, decisions, dependencies, risks, and open questions. Choose a specialist branch from the actual change shape. Sequence independently verifiable milestones and name rollback or recovery boundaries. Do not convert tentative technology choices into requirements. Evidence: current-state findings, acceptance criteria, dependency map, and explicit uncertainty. Failure signs: activity lists without outcomes, hidden scope, invented stacks, or gates that cannot falsify success.`,
  'architecture-planning': `Model responsibilities, state, data and control flow, trust boundaries, failure behavior, operational qualities, and likely change axes before selecting components. Compare viable alternatives against explicit constraints. Record compatibility seams, observability, deployment implications, and irreversible decisions. Prefer the least complex design satisfying demonstrated needs. Evidence: boundary and flow model, quality scenarios, tradeoff record, and validation plan. Reject diagrams without ownership, fashionable decomposition, and abstractions justified only by hypothetical scale.`,
  'migration-planning': `Inventory producers, consumers, persisted state, versions, compatibility promises, and recovery limits. Design staged coexistence, translation or backfill, validation, cutover, rollback, reconciliation, and cleanup. Keep each stage safe to pause and distinguish reversible deployment from irreversible transformation. Exercise mixed-version and interrupted states. Evidence: compatibility matrix, inventory counts, stage gates, rollback rehearsal, and reconciliation results. Reject big-bang transitions, unbounded dual writes, or cleanup scheduled before proof.`,
  'release-planning': `Define release units, environments, dependencies, approvals, user impact, telemetry, ownership, and support readiness. Specify preflight evidence, rollout increments, observation windows, stop thresholds, rollback mechanics, and post-release confirmation. Treat deployment, activation, adoption, and successful operation as different states. Evidence: signed gates, version identity, health and product signals, rollback rehearsal, and owner roster. Reject build-success-as-release-success and rollouts without observable stop conditions.`,
  implementation: `Inspect the actual integration surface, conventions, ownership, supported environments, and tests. Select the branch matching the change. Make the smallest complete change, including invalid input, failure, cancellation, cleanup, compatibility, and observability where risk demands them. Reuse established boundaries; do not introduce parallel architecture or unsupported dependencies. Evidence: coherent diff, behavior checks, and explicit skipped gates. Failure signs: scaffolding without a working path, happy-path-only behavior, or broad cleanup hiding the requested change.`,
  'feature-implementation': `Trace the requested capability end to end: entry, validation, state, side effects, output, feedback, errors, recovery, and authorization. Implement a vertical slice through existing contracts and components. Cover boundary inputs, partial failure, cancellation, persistence, and observability proportionately. Evidence: acceptance scenarios in the real medium, negative-path results, and relevant regression gates. Reject disconnected layers, placeholder success states, and speculative generalization beyond the task.`,
  'refactor-implementation': `Define external behavior and compatibility invariants before editing. Characterize uncertain behavior, then move in reviewable steps that reduce complexity rather than relocate it. Preserve public contracts unless change is authorized; remove obsolete paths and prove no duplicate authority remains. Evidence: characterization checks, structural improvement, invariant results, and focused diff review. Reject simultaneous unrelated features, abstraction for its own sake, and success claims based only on compilation.`,
  'integration-implementation': `Confirm both sides from authoritative contracts or observed behavior. Isolate translation, identity, lifecycle, versioning, timeouts, retries, idempotency, cancellation, and partial failure at the boundary. Preserve source-reported truth and keep missing values unknown. Evidence: contract fixtures, degraded-dependency tests, compatibility cases, and traceable error behavior. Reject guessed provider metadata, infinite retries, leaky transport concerns, and mocks as the sole proof of integration.`,
  debugging: `Establish observed versus expected behavior, environment identity, frequency, and earliest divergence. Preserve raw evidence, form falsifiable hypotheses, and use discriminating checks to reduce uncertainty. Select the specialist matching the failure mechanism. Repair the owning cause narrowly and verify neighboring behavior. Evidence: reproduction or stable signature, causal chain, regression check, and limitations. Reject symptom patches, random edits, and non-reproduction presented as proof.`,
  'deterministic-debugging': `Minimize input and execution path. Trace invariants and state transitions to the first wrong value or decision, comparing known-good and failing paths where possible. Inspect parsing, validation, lifecycle, ownership, and contract assumptions. Evidence: minimal reproduction, first causal divergence, repaired invariant, and regression case. Reject fixing only the final exception or expanding scope before the deterministic path is understood.`,
  'concurrency-debugging': `Model actors, shared resources, ownership, synchronization, happens-before relations, cancellation, and teardown. Capture schedules or traces where possible and vary timing systematically. Repair the violated ordering or ownership invariant rather than adding arbitrary delay. Evidence: concurrency timeline, race or wait relation, stress regression, and cleanup proof. Reject sleep-based fixes, single successful runs, and unsynchronized logging interpreted as total order.`,
  'distributed-debugging': `Correlate identities, versions, requests, messages, retries, state transitions, and clocks across boundaries. Account for loss, delay, duplication, reordering, partitions, stale reads, and split ownership. Reconstruct causality without trusting wall-clock order alone. Evidence: cross-boundary trace, failure timeline, state reconciliation, and recovery result. Reject single-service explanations unsupported by end-to-end evidence and fixes that merely amplify retries.`,
  'performance-debugging': `Reproduce with a controlled representative workload, baseline, and budget. Profile before optimizing; separate cold start, steady state, contention, saturation, allocation, I/O, and cleanup. Change one causal factor at a time and compare equivalent builds with variance. Evidence: profiles, raw measurements, workload definition, resource accounting, and budget delta. Reject intuition-only optimization, incomparable runs, averages hiding tails, and microbenchmarks substituted for product behavior.`,
  'hardware-runtime-debugging': `Record exact hardware, firmware, driver, runtime, topology, workload, and safety boundaries. Separate host, runtime, driver, transport, and device hypotheses. Begin with non-disruptive simulation or diagnostic gates and preserve traces. Evidence: environment identity, layer-localizing experiment, repeatable artifact, and clearly labeled simulated or physical proof. Reject risky escalation without need, emulator success as hardware proof, and conclusions that ignore thermal, timing, reset, or resource state.`,
  verification: `Map each material claim and acceptance criterion to an observable check. Choose branches by risk and medium, run the closest trustworthy environment, and inspect success, negative, recovery, and cleanup behavior. Record exact results and distinguish passed, failed, skipped, unavailable, simulated, and inferred evidence. Reject test-count theater, stale artifacts, and claims broader than the exercised surface.`,
  'functional-verification': `Exercise representative success, boundaries, invalid input, failure, cancellation, persistence, authorization, and recovery. Verify externally observable effects and durable state, not only internal calls. Evidence: claim-to-case mapping, exact outputs, side effects, negative cases, and regression results. Reject happy-path-only proof, assertions against implementation details, and mocks that bypass the behavior under claim.`,
  'visual-verification': `Inspect the actual rendering medium at representative sizes, content lengths, themes, densities, and input modes. Cover loading, empty, error, disabled, focused, overflow, resize, and interruption states. Pair captures with behavioral and semantic inspection. Evidence: runtime images or recordings, state matrix, and noted platform limits. Reject a single ideal screenshot, browser substitution for native proof, and aesthetics reviewed without interaction states.`,
  'accessibility-verification': `Combine automated checks with keyboard or alternative input, focus order, semantics, names and relationships, contrast, scaling, motion, error recovery, and representative assistive technology. Validate equivalent task completion, not merely rule counts. Evidence: manual task results, automated findings, environment identity, and residual limitations. Reject automated success as complete proof, color-only inspection, and inaccessible custom controls excused by visual polish.`,
  'reliability-verification': `Inject realistic faults and pressure; exercise restart, reconnect, replay, timeout, cancellation, partial availability, durability, cleanup, and sustained operation. Confirm observability distinguishes healthy, degraded, recovering, and failed states. Evidence: fault matrix, recovery timing, state integrity, soak artifacts, and objective comparison. Reject one clean run, fault injection without recovery assertions, and availability claims derived only from unit tests.`,
  'security-verification': `Test identities, roles, denied paths, isolation, secret exposure, injection surfaces, unsafe defaults, auditability, and fail-closed behavior at the enforcing layer. Include positive and negative authorization cases and boundary bypass attempts. Evidence: exact enforcement results, trust-boundary traces, and residual risk. Reject prompt wording, hidden UI, or client validation as enforcement; never let skill metadata grant authority.`,
  'performance-verification': `Define workload, environment, budget, warmup, sampling, variance, and comparison rules before measuring. Cover cold, warm, steady, peak, degraded, and cleanup behavior as relevant. Report distributions and resource costs, not averages alone. Evidence: reproducible protocol, raw artifacts, percentile and variance results, budget decision, and limitations. Reject cherry-picked runs, changed environments, and synthetic results generalized without validation.`,
  'documents-communication': `Identify audience, required decision or action, medium, authority, lifecycle, and accessibility needs. Preserve source truth, distinguish fact from inference, expose uncertainty and ownership, and select a specialist by reader purpose. Structure for retrieval and action rather than decorative prose. Evidence: factual review, audience walkthrough, format validation, and source traceability. Reject invented certainty, buried asks, and file-format labels treated as professional disciplines.`,
  'technical-communication': `State scope, context, constraints, mechanism or architecture, decisions, alternatives, interfaces, risks, evidence, and unresolved work. Use diagrams and tables only when relationships become clearer. Keep examples executable or label them illustrative. Evidence: technical review, source-linked claims, validated examples, and terminology consistency. Reject unexplained jargon, stale implementation detail, and diagrams without ownership or flow.`,
  'executive-communication': `Lead with the outcome, decision, or status. Connect evidence to impact, options, tradeoffs, risk, timing, ownership, and explicit asks. Include technical detail only where it changes the decision and distinguish confidence from certainty. Evidence: decision clarity review, source-backed metrics, named owner, and next decision point. Reject activity dumps, vanity metrics, hidden risk, and recommendations without alternatives or consequences.`,
  'instructional-communication': `Define prerequisites, starting state, goal, ordered actions, decision points, expected feedback, safety warnings, failure recovery, and completion checks. Test the instructions from the intended reader environment and remove hidden expert assumptions. Evidence: walkthrough result, validated commands or actions, recovery exercise, and completion proof. Reject unexplained leaps, destructive steps without warnings, and tutorials that end before verification.`,
  'reference-communication': `Organize for stable lookup. Define names, types, units, defaults, constraints, lifecycle, compatibility, errors, examples, and version scope. Derive from authoritative definitions where possible and test examples. Evidence: source comparison, coverage review, example execution, and version identity. Reject narrative that obscures lookup, undocumented defaults, ambiguous units, stale generated material, and examples inconsistent with the normative contract.`,
} as const satisfies Record<string, string>;

const planningMethod = ` Method: begin with a written problem frame and evidence inventory; enumerate constraints and competing options; test the highest-risk assumption with the cheapest representative probe; then sequence work by dependency and learning value. For every milestone name its owner, input, observable output, decision gate, and recovery path. Reconcile the plan against repository and runtime evidence before execution and again when evidence changes. Preserve rejected options and why they lost so later agents do not silently reopen settled choices. A plan is incomplete when success cannot be observed, an irreversible step lacks a recovery strategy, a dependency has no owner, or estimates conceal unresolved discovery.`;
const implementationMethod = ` Method: trace one representative request or event across every changed boundary before editing, then implement in dependency order and keep the system runnable after each coherent increment. Inspect callers and consumers whenever a contract changes. Exercise success, boundary, denied, interrupted, and recovery paths in the closest supported environment. Preserve exact diffs and test output, and explain any generated or migrated state. Stop and reassess when the change requires duplicate sources of truth, bypasses an owning abstraction, broadens permissions, or cannot be verified independently. Completion requires observable behavior plus cleanup of superseded paths; compilation, mocks, scaffolding, and code appearance alone are insufficient evidence.`;
const debuggingMethod = ` Method: freeze relevant environment identity and collect the earliest trustworthy symptom before changing code. Rank hypotheses by explanatory power and use one discriminating experiment at a time, recording predicted and actual outcomes. Reduce the case while preserving the failure, trace backward from the first divergence, and inspect the authority boundary that owns the violated invariant. After repair, rerun the original reproduction, a focused regression, neighboring behavior, and the relevant runtime gate. Treat disappeared symptoms, added retries, longer delays, swallowed errors, or reset state as containment rather than root-cause proof unless the causal model demonstrates otherwise.`;
const verificationMethod = ` Method: create a claim ledger linking each acceptance statement and material risk to a check, environment, oracle, artifact, and confidence limit. Run cheap deterministic gates first, then representative integration or runtime checks, without substituting one evidence class for another. Preserve versions, configuration, inputs, commands, timestamps, and raw outputs so another operator can reproduce the result. Investigate flaky or contradictory evidence instead of averaging it away. Report untested branches and environmental gaps beside passes. Verification fails when the oracle merely repeats implementation logic, fixtures bypass the boundary under claim, artifacts are stale, or the conclusion extends beyond the exercised conditions.`;
const communicationMethod = ` Method: write a one-sentence reader outcome, inventory authoritative sources, and choose an information sequence matching how the audience will decide, act, learn, or look something up. Draft headings as questions the reader must answer, attach claims to evidence, label inference and uncertainty, and make ownership and next action explicit. Validate examples, links, terminology, units, version scope, and accessibility in the delivered medium. Ask a representative reader or independent reviewer to perform the intended task using only the document. Revise where they hesitate or infer hidden knowledge. Communication fails when polish masks missing evidence, summaries contradict details, essential warnings appear after actions, or the document cannot survive its source changing.`;

const planningNames = new Set([
  'planning',
  'architecture-planning',
  'migration-planning',
  'release-planning',
]);
const implementationNames = new Set([
  'implementation',
  'feature-implementation',
  'refactor-implementation',
  'integration-implementation',
]);
const debuggingNames = new Set([
  'debugging',
  'deterministic-debugging',
  'concurrency-debugging',
  'distributed-debugging',
  'performance-debugging',
  'hardware-runtime-debugging',
]);
const verificationNames = new Set([
  'verification',
  'functional-verification',
  'visual-verification',
  'accessibility-verification',
  'reliability-verification',
  'security-verification',
  'performance-verification',
]);

export const DELIVERY_SKILL_PLAYBOOKS = Object.fromEntries(
  Object.entries(CORE_DELIVERY_PLAYBOOKS).map(([name, playbook]) => [
    name,
    `${playbook}${planningNames.has(name) ? planningMethod : implementationNames.has(name) ? implementationMethod : debuggingNames.has(name) ? debuggingMethod : verificationNames.has(name) ? verificationMethod : communicationMethod}`,
  ]),
) as { [Name in keyof typeof CORE_DELIVERY_PLAYBOOKS]: string };

export type DeliverySkillPlaybookName = keyof typeof DELIVERY_SKILL_PLAYBOOKS;
