/** Luna-authored delivery playbooks. Proposal data only; not wired into runtime. */
const CORE_DELIVERY_PLAYBOOKS = {
  planning: `Establish outcome, stakeholders, constraints, authority, current evidence, and done conditions. Separate facts, assumptions, decisions, dependencies, risks, and open questions. Choose a specialist branch from the actual change shape. Sequence independently verifiable milestones and name rollback or recovery boundaries. Do not convert tentative technology choices into requirements. Evidence: current-state findings, acceptance criteria, dependency map, and explicit uncertainty. Failure signs: activity lists without outcomes, hidden scope, invented stacks, or gates that cannot falsify success.`,
  'architecture-planning': `Model responsibilities, state, data and control flow, trust boundaries, failure behavior, operational qualities, and likely change axes before selecting components. Compare viable alternatives against explicit constraints. Record compatibility seams, observability, deployment implications, and irreversible decisions. Prefer the least complex design satisfying demonstrated needs. Evidence: boundary and flow model, quality scenarios, tradeoff record, and validation plan. Reject diagrams without ownership, fashionable decomposition, and abstractions justified only by hypothetical scale.`,
  'migration-planning': `Inventory producers, consumers, persisted state, versions, compatibility promises, and recovery limits. Design staged coexistence, translation or backfill, validation, cutover, rollback, reconciliation, and cleanup. Keep each stage safe to pause and distinguish reversible deployment from irreversible transformation. Exercise mixed-version and interrupted states. Evidence: compatibility matrix, inventory counts, stage gates, rollback rehearsal, and reconciliation results. Reject big-bang transitions, unbounded dual writes, or cleanup scheduled before proof.`,
  'release-planning': `Define release units, environments, dependencies, approvals, user impact, telemetry, ownership, and support readiness. Specify preflight evidence, rollout increments, observation windows, stop thresholds, rollback mechanics, and post-release confirmation. Treat deployment, activation, adoption, and successful operation as different states. Evidence: signed gates, version identity, health and product signals, rollback rehearsal, and owner roster. Reject build-success-as-release-success and rollouts without observable stop conditions.`,
  implementation: `Inspect the actual integration surface, conventions, ownership, supported environments, and tests. Select the branch matching the change. Make the smallest complete change, including invalid input, failure, cancellation, cleanup, compatibility, and observability where risk demands them. Reuse established boundaries; do not introduce parallel architecture or unsupported dependencies. Evidence: coherent diff, behavior checks, and explicit skipped gates. Failure signs: scaffolding without a working path, happy-path-only behavior, or broad cleanup hiding the requested change.`,
  'feature-implementation': `Trace the requested capability end to end: entry, validation, state, side effects, output, feedback, errors, recovery, and authorization. Implement a vertical slice through existing contracts and components. Cover boundary inputs, partial failure, cancellation, persistence, and observability proportionately. Evidence: acceptance scenarios in the real medium, negative-path results, and relevant regression gates. Reject disconnected layers, placeholder success states, and speculative generalization beyond the task.`,
  'refactor-implementation': `Define external behavior and compatibility invariants before editing. Characterize uncertain behavior, then move in reviewable steps that reduce complexity rather than relocate it. Preserve public contracts unless change is authorized; remove obsolete paths and prove no duplicate authority remains. Evidence: characterization checks, structural improvement, invariant results, and focused diff review. Reject simultaneous unrelated features, abstraction for its own sake, and success claims based only on compilation.`,
  'integration-implementation': `Confirm both sides from authoritative contracts or observed behavior. Isolate translation, identity, lifecycle, versioning, timeouts, retries, idempotency, cancellation, and partial failure at the boundary. Preserve source-reported truth and keep missing values unknown. Evidence: contract fixtures, degraded-dependency tests, compatibility cases, and traceable error behavior. Reject guessed provider metadata, infinite retries, leaky transport concerns, and mocks as the sole proof of integration.`,
  debugging: `Establish observed versus expected behavior, environment identity, frequency, and earliest divergence. Preserve raw evidence, form falsifiable hypotheses, and use discriminating checks to reduce uncertainty. Select the specialist matching the failure mechanism. Repair the owning cause narrowly and verify neighboring behavior. Evidence: reproduction or stable signature, causal chain, regression check, and limitations. Reject symptom patches, random edits, and non-reproduction presented as proof.`,
  'deterministic-debugging': `Minimize input and execution path. Trace invariants and state transitions to the first wrong value or decision, comparing known-good and failing paths where possible. Inspect parsing, validation, lifecycle, ownership, and contract assumptions. Evidence: minimal reproduction, first causal divergence, repaired invariant, and regression case. Reject fixing only the final exception or expanding scope before the deterministic path is understood.`,
  'concurrency-debugging': `Model actors, shared resources, ownership, synchronization, happens-before relations, cancellation, and teardown. Capture schedules or traces where possible and vary timing systematically. Repair the violated ordering or ownership invariant rather than adding arbitrary delay. Evidence: concurrency timeline, race or wait relation, stress regression, and cleanup proof. Reject sleep-based fixes, single successful runs, and unsynchronized logging interpreted as total order.`,
  'distributed-debugging': `Correlate identities, versions, requests, messages, retries, state transitions, and clocks across boundaries. Account for loss, delay, duplication, reordering, partitions, stale reads, and split ownership. Reconstruct causality without trusting wall-clock order alone. Evidence: cross-boundary trace, failure timeline, state reconciliation, and recovery result. Reject single-service explanations unsupported by end-to-end evidence and fixes that merely amplify retries.`,
  'performance-debugging': `Reproduce with a controlled representative workload, baseline, and budget. Profile before optimizing; separate cold start, steady state, contention, saturation, allocation, I/O, and cleanup. Change one causal factor at a time and compare equivalent builds with variance. Evidence: profiles, raw measurements, workload definition, resource accounting, and budget delta. Reject intuition-only optimization, incomparable runs, averages hiding tails, and microbenchmarks substituted for product behavior.`,
  'hardware-runtime-debugging': `Record exact hardware, firmware, driver, runtime, topology, workload, and safety boundaries. Separate host, runtime, driver, transport, and device hypotheses. Begin with non-disruptive simulation or diagnostic gates and preserve traces. Evidence: environment identity, layer-localizing experiment, repeatable artifact, and clearly labeled simulated or physical proof. Reject risky escalation without need, emulator success as hardware proof, and conclusions that ignore thermal, timing, reset, or resource state.`,
  verification: `Map each material claim and acceptance criterion to an observable check. Choose branches by risk and medium, run the closest trustworthy environment, and inspect success, negative, recovery, and cleanup behavior. Record exact results and distinguish passed, failed, skipped, unavailable, simulated, and inferred evidence. Reject test-count theater, stale artifacts, and claims broader than the exercised surface.`,
  'functional-verification': `Exercise representative success, boundaries, invalid input, failure, cancellation, persistence, authorization, and recovery. Verify externally observable effects and durable state, not only internal calls. Evidence: claim-to-case mapping, exact outputs, side effects, negative cases, and regression results. Reject happy-path-only proof, assertions against implementation details, and mocks that bypass the behavior under claim.`,
  'visual-verification': `Inspect the actual target medium at representative sizes, content lengths, themes, densities, and input modes. Cover applicable loading, empty, error, disabled, focused or selected, overflow, resize, and interruption states. First audit universal claims: hierarchy, repetition, token consistency, asset purpose, legibility, and motion rationale. Then use only the confirmed medium's checks: browser reflow and semantics; native scaling, shortcuts, and window state; terminal plain-text, color-off, and automation behavior; game/spatial attention, comfort, and frame budget; embedded physical-control, safe-state, and environmental legibility. Mark each visual claim passed, failed, or unavailable. Pair captures or medium-appropriate artifacts with behavioral and semantic inspection. Evidence: runtime artifacts, state matrix, visual-direction claim audit, and noted platform limits. Reject a single ideal screenshot, browser substitution for native proof, web prescriptions in another medium, checklist theater, and aesthetics reviewed without interaction states.`,
  'accessibility-verification': `Combine automated checks with keyboard or alternative input, focus order, semantics, names and relationships, contrast, scaling, motion, error recovery, and representative assistive technology. Validate equivalent task completion, not merely rule counts. Evidence: manual task results, automated findings, environment identity, and residual limitations. Reject automated success as complete proof, color-only inspection, and inaccessible custom controls excused by visual polish.`,
  'reliability-verification': `Inject realistic faults and pressure; exercise restart, reconnect, replay, timeout, cancellation, partial availability, durability, cleanup, and sustained operation. Confirm observability distinguishes healthy, degraded, recovering, and failed states. Evidence: fault matrix, recovery timing, state integrity, soak artifacts, and objective comparison. Reject one clean run, fault injection without recovery assertions, and availability claims derived only from unit tests.`,
  'security-verification': `Test identities, roles, denied paths, isolation, secret exposure, injection surfaces, unsafe defaults, auditability, and fail-closed behavior at the enforcing layer. Include positive and negative authorization cases and boundary bypass attempts. Evidence: exact enforcement results, trust-boundary traces, and residual risk. Reject prompt wording, hidden UI, or client validation as enforcement; never let skill metadata grant authority.`,
  'performance-verification': `Define workload, environment, budget, warmup, sampling, variance, and comparison rules before measuring. Cover cold, warm, steady, peak, degraded, and cleanup behavior as relevant. Report distributions and resource costs, not averages alone. Evidence: reproducible protocol, raw artifacts, percentile and variance results, budget decision, and limitations. Reject cherry-picked runs, changed environments, and synthetic results generalized without validation.`,
  'documents-communication': `Identify audience, required decision or action, medium, authority, lifecycle, and accessibility needs. Preserve source truth, distinguish fact from inference, expose uncertainty and ownership, and select a specialist by reader purpose. Structure for retrieval and action rather than decorative prose. Evidence: factual review, audience walkthrough, format validation, and source traceability. Reject invented certainty, buried asks, and file-format labels treated as professional disciplines.`,
  'technical-communication': `State scope, context, constraints, mechanism or architecture, decisions, alternatives, interfaces, risks, evidence, and unresolved work. Use diagrams and tables only when relationships become clearer. Keep examples executable or label them illustrative. Evidence: technical review, source-linked claims, validated examples, and terminology consistency. Reject unexplained jargon, stale implementation detail, and diagrams without ownership or flow.`,
  'executive-communication': `Lead with the outcome, decision, or status. Connect evidence to impact, options, tradeoffs, risk, timing, ownership, and explicit asks. Include technical detail only where it changes the decision and distinguish confidence from certainty. Evidence: decision clarity review, source-backed metrics, named owner, and next decision point. Reject activity dumps, vanity metrics, hidden risk, and recommendations without alternatives or consequences.`,
  'instructional-communication': `Define prerequisites, starting state, goal, ordered actions, decision points, expected feedback, safety warnings, failure recovery, and completion checks. Test the instructions from the intended reader environment and remove hidden expert assumptions. Evidence: walkthrough result, validated commands or actions, recovery exercise, and completion proof. Reject unexplained leaps, destructive steps without warnings, and tutorials that end before verification.`,
  'reference-communication': `Organize for stable lookup. Define names, types, units, defaults, constraints, lifecycle, compatibility, errors, examples, and version scope. Derive from authoritative definitions where possible and test examples. Evidence: source comparison, coverage review, example execution, and version identity. Reject narrative that obscures lookup, undocumented defaults, ambiguous units, stale generated material, and examples inconsistent with the normative contract.`,
} as const satisfies Record<string, string>;

const planningMethod = ` Operating method:

1. Frame the decision before proposing work. Write the desired outcome in observable terms, identify the people or systems affected, and state who may approve scope, spend, risk, migration, and release. Inventory repository evidence, runtime evidence, user reports, contracts, policy, and known deadlines. Label every statement as observed fact, supported inference, assumption, constraint, preference, or open question. Never silently promote a preference or tentative implementation idea into a requirement. If the request is ambiguous but a reversible discovery step is safe, perform that discovery and update the frame; ask for direction only when different answers would authorize materially different outcomes.

2. Define success and non-goals. Translate the outcome into acceptance criteria that name the actor, starting state, action, observable result, and relevant failure or recovery behavior. Add explicit non-goals and compatibility obligations so adjacent improvements do not consume the task. For each criterion, name the intended verification medium and evidence class. A unit test cannot establish a native-window claim, a diagram cannot establish runtime behavior, and an estimate cannot establish capacity. When success depends on an external team, service, credential, device, or decision, record that dependency separately rather than disguising it as implementation work.

3. Map the current system. Identify ownership boundaries, sources of truth, entry points, state transitions, consumers, data lifetimes, trust boundaries, release paths, and existing test or observability surfaces. Trace at least one representative flow end to end. Record uncertainty where the current state is inferred instead of observed. Prefer existing architecture, naming, controls, and operational conventions unless evidence shows they are the problem. Do not plan a parallel subsystem merely because the current one is unfamiliar.

4. Generate and compare credible options. Include the smallest viable change, at least one materially different alternative when the decision is consequential, and the option to defer or gather more evidence. Compare options against the same criteria: user value, correctness, safety, compatibility, reversibility, complexity, operational burden, delivery cost, and evidence quality. State which constraints eliminate an option and which tradeoffs remain subjective. Avoid false precision in estimates; express ranges and confidence, with discovery items for the uncertainty driving the range.

5. Retire risk early. Rank assumptions by impact and uncertainty. Choose the cheapest representative probe that can falsify the riskiest assumption: inspect a contract, build a thin spike, replay production-shaped data safely, test a migration copy, or exercise the actual medium. Define the probe's stop condition before running it. A spike produces evidence, not production code by default. If the probe contradicts the plan, revise the decision record and downstream milestones instead of preserving sunk work.

6. Sequence milestones by dependency and learning value. Each milestone must name its purpose, owner, prerequisites, inputs, bounded scope, observable output, verification gate, and recovery path. Keep milestones independently reviewable and leave the system in a coherent state. Put contract decisions and high-risk boundary validation before broad implementation; put irreversible transformation only after compatibility and restoration paths are proven. Distinguish work that may run in parallel from work that only appears independent but edits the same authority or relies on the same unresolved decision.

7. Make state transitions explicit. Use a compact matrix where useful: current state, proposed state, trigger, invariant, observable signal, failure state, and recovery action. For migrations and releases, include old-only, mixed-version, new-only, interrupted, rolled-back, and cleanup states. For architecture, include healthy, degraded, dependency-unavailable, overloaded, and recovery states. Do not use happy-path diagrams as substitutes for lifecycle analysis.

8. Establish control points. Before execution, define go, pause, rollback, and abort conditions using observable thresholds rather than intuition. Name the person or automation allowed to make each decision. Protect irreversible actions with backups, dry runs, bounded batches, reconciliation, or explicit authorization as appropriate. Do not call a backup a recovery plan until restoration has been exercised or its limitations are disclosed. Do not schedule removal of compatibility paths before adoption and correctness are independently confirmed.

9. Maintain the plan as evidence changes. Record decisions, rejected options, owners, and dated assumptions. At each milestone, compare actual evidence with the problem frame and replan when scope, risk, or feasibility changes. Separate progress reporting from outcome reporting: completed activities do not prove the intended state exists. Escalate a blocker with the exact missing authority or artifact, the safe work already exhausted, and the decision needed; do not invent credentials, approvals, provider behavior, or user intent to keep the plan moving.

10. Verify plan quality before handoff. Walk one success path, one invalid or denied path, one interruption, and one recovery through the proposed sequence. Confirm every acceptance criterion maps to a milestone and every material risk maps to a probe, guardrail, or explicitly accepted residual risk. Confirm dependencies have owners, estimates expose discovery, and deliverables name their evidence. Example: instead of "update storage, test, deploy," specify "introduce backward-compatible reader, verify old and new records, backfill a bounded copy with reconciliation, canary readers, observe error and mismatch thresholds, then remove the old writer only after rollback expiry." A plan is not ready when it is an activity list, assumes uninterrupted success, lacks a falsifiable gate, or leaves an irreversible step without recovery.`;
const implementationMethod = ` Operating method:

1. Establish the contract of the change. Restate the user-visible or system-visible outcome, the authorized scope, compatibility requirements, and conditions of completion. Inspect repository guidance, existing abstractions, neighboring implementations, tests, generated-code rules, dependency policy, and supported environments before editing. Identify which component owns validation, state, side effects, authorization, presentation, and cleanup. If ownership is unclear, trace callers and consumers rather than creating a new source of truth.

2. Trace a representative flow end to end. Follow one real request, event, command, render, or state transition from entry through validation, persistence or side effects, output, error reporting, and teardown. Record data shapes and lifecycle boundaries. Inspect both producers and consumers of every contract you expect to change. Treat undocumented observed behavior as evidence to characterize, not automatically as a promise. Never guess provider metadata, protocol fields, model identity, file formats, or security semantics when authoritative or runtime evidence can be obtained.

3. Choose the smallest complete design. Prefer extending the owning abstraction and reusing native controls, tokens, types, and error conventions. A complete vertical slice includes validation, authorized execution, feedback, failure behavior, cancellation where applicable, persistence semantics, cleanup, and observability proportional to risk. Avoid speculative frameworks, duplicate stores, broad renaming, unrelated cleanup, or a generic abstraction supported by only one imagined future case. When a new abstraction is justified, document the repeated variation it owns and the invariant it enforces.

4. Plan coherent increments. Order work so contracts and types stabilize before dependent behavior, and keep the project runnable after each meaningful increment. Separate mechanical moves from behavior changes when practical. For risky transformations, add compatibility or characterization checks before replacing behavior. If generated artifacts or migrations are involved, identify the authoritative source, deterministic regeneration command, review strategy, and rollback implications. Never hand-edit derived output without updating its source unless the project explicitly requires it.

5. Implement invariants at the enforcing boundary. Validate untrusted input at ingress; enforce authorization server-side or at the actual capability boundary; keep secrets out of logs and client state; preserve provider-emitted truth; make retry and idempotency semantics explicit; bound timeouts, resource use, and queues. UI hiding, prompt instructions, TypeScript types, and client validation are usability aids, not security enforcement. Missing or uncertain data remains unknown rather than receiving a plausible invented fallback.

6. Handle the full lifecycle. Deliberately implement initial, loading, ready, empty, invalid, denied, partial, interrupted, retrying, stale, completed, and cleanup states when the medium or operation permits them. Define ownership of cancellation, subscriptions, handles, temporary files, transactions, locks, and background work. Make repeated invocation safe when required. Preserve user work during recoverable errors and surface an actionable recovery path. Do not swallow errors, loop indefinitely, or report success before durable effects and reconciliation complete.

7. Use a behavior matrix for boundary cases. For each relevant case record input or starting state, expected transition, visible output, side effect, cleanup, and oracle. At minimum exercise normal input, boundary input, malformed input, denied authority, dependency failure, cancellation or interruption, retry or replay, and restoration. Example: a settings save is incomplete if the button works only with valid data; it must prevent duplicate submission, preserve edits on server rejection, show the source-reported error, refresh canonical persisted state after success, and remain correct after reload.

8. Observe while implementing. Add or preserve structured errors, correlation identifiers, state signals, metrics, and logs only where they help operators distinguish healthy, degraded, recovering, and failed behavior. Do not log secrets or large sensitive payloads. Make failure messages specific enough to identify the boundary and safe next action. Temporary diagnostic instrumentation must either be removed or intentionally converted into supported observability before completion.

9. Verify in layers without confusing them. Run focused static checks and unit tests during development, then contract, integration, and real-medium checks matching the claim. Exercise negative and recovery paths, not just a successful demonstration. Inspect durable state and externally visible effects rather than only mocked calls. When changing UI, inspect representative sizes, themes, focus, keyboard behavior, and error states. When changing native behavior, prove a fresh native process or window rather than substituting browser health. Record skipped gates and why; never present an unavailable environment as a pass.

10. Review the diff as a system change. Check every modified contract's callers and consumers, public compatibility, data migration, error paths, cleanup, dependency additions, configuration, documentation, and dead code. Confirm no temporary fallback, old authority, debug bypass, or duplicate path remains unless coexistence is intentional and bounded. Keep unrelated user changes intact. Stop and reassess if implementation requires broad new authority, irreversible external action, an unsupported dependency, or a second source of truth.

11. Recover deliberately from failed approaches. Revert only your bounded experimental change, preserve evidence explaining why it failed, and update the causal model before trying another design. Do not stack patches on an unexplained failure. If a compatibility shim is needed, give it ownership, telemetry, removal criteria, and a deadline or version boundary. If the ideal fix is blocked, distinguish safe containment from root-cause repair and state the residual risk.

12. Declare completion from behavior, not code volume. Handoff must include the outcome, important design decisions, files or boundaries changed, exact checks and results, environmental limits, and remaining risks. Compilation proves type-level consistency only; mocks prove the harnessed path only; scaffolding proves nothing about user behavior. Example: "endpoint added" is not complete until the supported client reaches it, invalid and unauthorized calls fail correctly, cancellation and dependency errors recover, persisted effects match the contract, and the observable product path passes in its intended environment.`;
const debuggingMethod = ` Operating method:

1. Preserve the incident before changing it. Record observed behavior verbatim, expected behavior, impact, frequency, first known occurrence, environment identity, versions, configuration, input, account or data shape, and whether the failure is ongoing. Capture raw logs, traces, screenshots, dumps, exit status, request identifiers, and timestamps with sensitive material redacted. Distinguish direct observation from a reporter's interpretation. Do not restart, clear state, upgrade dependencies, or add retries until volatile evidence is preserved unless safety requires immediate containment.

2. Establish a stable signature. Reproduce the problem when safe, or define a uniquely identifying symptom when reproduction is destructive, intermittent, or externally controlled. Determine whether the failure follows the input, user, process, host, device, version, region, time window, or dependency. Compare a known-good case using the same observation points. A failure disappearing after a reset narrows hypotheses but does not prove the reset fixed the cause.

3. Minimize without erasing the mechanism. Reduce data, configuration, concurrency, topology, and execution path one dimension at a time while confirming the signature remains. Record the smallest reproducer and the last reduction that made the problem disappear. Preserve timing, ordering, authorization, persistence, and resource pressure when those may be causal. Synthetic reproduction is useful only if its relationship to the original failure is explicit.

4. Build a causal timeline. Trace the earliest trustworthy input through state transitions and boundary crossings until expected and actual behavior first diverge. For asynchronous or distributed behavior, correlate stable identifiers and causal relationships rather than trusting wall-clock order. For concurrent behavior, model actors, resource ownership, waits, cancellation, and teardown. For hardware or runtime behavior, freeze device, firmware, driver, topology, resource state, and workload identity. The final exception is often downstream damage, not the first cause.

5. Form competing falsifiable hypotheses. Each hypothesis must name a mechanism, predict an observation that differs from alternatives, and identify the cheapest safe discriminating experiment. Rank by explanatory coverage and evidence, not familiarity. Include at least one hypothesis outside the most obvious layer when the flow crosses boundaries. Do not list vague categories such as "race condition" or "cache issue" without the violated ordering or invalidation mechanism they predict.

6. Run one discriminating experiment at a time. State the predicted result for each live hypothesis before the check, control unrelated variables, preserve output, and update the hypothesis table afterward. A useful table has hypothesis, supporting evidence, conflicting evidence, experiment, prediction, actual result, and status. Instrument at the suspected boundary rather than flooding the whole system with logs. Never interpret unsynchronized logging as a total event order or a single successful stress run as absence of a race.

7. Separate containment, correction, and prevention. Containment reduces current harm: disable a path, bound retries, shed load, restore a known-good version, or isolate a device. Correction repairs the owning violated invariant. Prevention adds regression coverage, observability, validation, or operational safeguards. Label each honestly. Longer sleeps, broader catches, swallowed errors, state deletion, repeated retries, and process restarts are not root-cause fixes unless the causal model establishes why they restore the invariant without masking corruption or leaks.

8. Repair at the authority boundary. Make the narrowest coherent change where ownership, ordering, validation, identity, or lifecycle is actually enforced. Avoid patching every symptom site. Preserve compatibility unless change is authorized. For retries, specify eligibility, idempotency, backoff, maximum attempts, and terminal behavior. For concurrency, repair synchronization or ownership rather than timing. For distributed state, define reconciliation and duplicate handling. For performance, change the profiled bottleneck and remeasure equivalent workloads. For hardware, begin with non-disruptive gates and do not generalize simulation to physical proof.

9. Prove the causal link. First rerun the exact original reproducer without weakening its oracle. Then run a focused regression that fails before and passes after the repair, neighboring cases that could regress, and the closest supported integration or runtime gate. Repeat enough to characterize intermittency and variance. Force the relevant error, cancellation, restart, retry, cleanup, or pressure condition. Verify durable state and resource release after the run. If reproduction is unavailable, state that confidence is based on the stable signature and causal evidence, not a confirmed before-and-after reproduction.

10. Challenge the fix. Ask what other path shares the violated invariant, what stale state survives deployment, whether mixed versions can interact, whether the fix changes performance or authority, and whether instrumentation itself altered timing. Remove or intentionally retain diagnostic code. Review logs for secret exposure. If evidence conflicts, stop and investigate; do not average contradictory runs into a pass.

11. Recover from a wrong hypothesis cleanly. Restore only the bounded experiment, keep the evidence, and explain which prediction failed. Do not accumulate speculative edits. If emergency mitigation must remain, give it an owner, expiry condition, monitoring signal, and known cost. Escalate when the next experiment requires unsafe hardware action, production mutation, unavailable credentials, or authority outside scope, and specify exactly what evidence or approval is needed.

12. Report with calibrated confidence. Include the symptom, affected scope, environment, minimal reproducer or signature, first divergence, causal chain, fix, regression evidence, neighboring checks, and remaining uncertainty. Example: "adding a retry stopped failures" is inadequate; a strong result identifies the non-idempotent boundary, demonstrates the duplicate transition under a lost response, makes replay idempotent, forces that response loss in regression, and verifies one durable effect. Never equate inability to reproduce, quiet logs, or a green unrelated suite with resolution.`;
const verificationMethod = ` Operating method:

1. Start with claims, not available tests. Build a claim ledger from acceptance criteria, changed behavior, compatibility promises, security boundaries, operational qualities, and user-facing statements. For each claim record scope, risk, environment, preconditions, action, expected observation, independent oracle, artifact, and confidence limit. Split broad claims until one check can meaningfully falsify each part. "Works," "secure," "accessible," "fast," and "production ready" are bundles of claims, never single test outcomes.

2. Match evidence to the medium and layer. Static analysis supports source properties; unit tests support isolated logic; contract tests support boundary shapes; integration tests support cooperating components; runtime observation supports deployed behavior; browser evidence supports browser UI; a fresh native process and window support native-launch claims; physical-device runs support hardware claims. Simulation, mocks, screenshots, health endpoints, build success, and code inspection each have value but cannot substitute for a different evidence class. State when the closest environment is unavailable.

3. Establish trustworthy identity. Record source revision, build identity, package or binary version, configuration, feature flags, dependency versions, account role, data fixture, operating system, browser or runtime, device and driver where relevant, and time of execution. Ensure the artifact exercised was produced from the code under review. Reject stale screenshots, an old server behind a new frontend, cached generated output, or an already-running process whose provenance is unknown.

4. Define independent oracles. Prefer externally observable results, canonical persisted state, authoritative contracts, or an independent implementation over assertions that repeat the code's internal decisions. Confirm both the result and important side effects. A request returning success is insufficient if durable state is wrong; a rendered label is insufficient if keyboard operation or semantics fail; a log saying "authorized" is insufficient if the enforcing boundary can be bypassed. When no independent oracle exists, disclose the circularity and lower confidence.

5. Use a state and risk matrix. Cover representative success, boundary values, empty state, malformed input, denied authority, unavailable dependency, timeout, cancellation, retry or replay, stale state, interruption, restart, recovery, and cleanup as applicable. Add medium-specific states such as focus, overflow, scaling, color-off, reduced motion, mixed versions, resource pressure, or device reset. Each row should name starting state, action or fault, expected transition, observable result, durable effect, cleanup, and artifact. Omit irrelevant states deliberately rather than mechanically checking boxes.

6. Run gates in an efficient order. Begin with deterministic format, type, lint, schema, and focused unit checks to catch cheap failures. Continue to contract and integration checks, then representative runtime, visual, accessibility, reliability, security, performance, or hardware evidence according to the claim ledger. A cheap gate failing may block expensive checks, but a cheap gate passing never erases the need for the representative one. Preserve exact commands, exit status, and raw output.

7. Exercise negative and recovery behavior deliberately. Attempt invalid, unauthorized, repeated, interrupted, and out-of-order operations. Inject realistic faults at the boundary under claim, not solely inside a mock. Verify the system fails closed where authority or integrity is involved, retains actionable state where recovery is expected, and releases resources after cancellation or failure. Confirm observability distinguishes healthy, degraded, recovering, and failed states without leaking secrets.

8. Control performance and reliability evidence. Define workload, data size, warmup, duration, sampling, concurrency, environment, resource limits, and comparison rules before measurement. Separate cold start, warm steady state, peak, saturation, degradation, and cleanup. Report distributions, percentiles, error counts, throughput, and resource costs with variance rather than a favorable average. Change one causal factor at a time. A microbenchmark supports only its bounded operation until correlation with product behavior is shown.

9. Verify user interfaces as interactive systems. Inspect the real target at representative viewport or window sizes, themes, zoom or scaling, content lengths, and input modes. Cover loading, empty, error, disabled, focused, selected, overflow, resize, and interruption states. Check hierarchy, contrast, semantics, accessible names, relationships, focus order, keyboard or alternative input, error recovery, and task completion. Automated accessibility scans and ideal screenshots are inputs, not complete proof. Use native controls and product conventions expected by the repository; do not excuse an inaccessible custom control because it looks polished.

10. Verify security at the enforcing layer. Test distinct identities and roles, allowed and denied paths, object isolation, malformed and adversarial input, secret handling, audit records, and bypass attempts. Confirm client or prompt restrictions are backed by server-side or capability-level enforcement. Never let test fixtures, skill metadata, UI visibility, or caller-supplied role labels grant authority. Record residual risk and environmental assumptions without publishing exploit-enabling secret data.

11. Treat flaky and contradictory results as findings. Preserve each run and investigate correlations with order, timing, resources, shared state, cache, network, or environment. Do not rerun until green and report only the winner; do not average incompatible builds; do not weaken assertions to silence instability. Quarantine may protect the main suite temporarily, but it must retain ownership, impact, reproduction evidence, and an exit criterion. If an oracle is wrong, repair the oracle and rerun affected claims.

12. Confirm recovery and cleanup. After fault or cancellation, inspect transactions, files, subscriptions, locks, handles, temporary resources, background jobs, queues, and canonical state. Exercise restart or reconnect when the claim includes durability. For migrations and releases, test old-only, mixed-version, new-only, rollback, reconciliation, and cleanup boundaries. A rollback script is not proven until restoration is exercised on representative state or clearly labeled untested.

13. Report evidence with bounded language. Mark every ledger item passed, failed, skipped, unavailable, simulated, or inferred. Link the exact artifact and state what it proves, what it does not prove, and any platform or sample limitation. Separate local source health from deployment truth, emulator results from physical-device results, and observed capability from general guarantees. Never inflate test count into coverage or phrase an unavailable check as success.

14. Apply a final falsification review. Ask whether the same evidence could exist while the claim is false, whether fixtures bypassed the boundary, whether the artifact is current, whether success depended on preexisting state, and whether cleanup was observed. Example: a green health endpoint plus a stale window does not prove a fresh desktop launch; require a newly started persistent native PID, current window evidence, and the intended backend interaction. Verification is complete only when material claims have suitable evidence and failures or gaps remain visible beside passes.`;
const communicationMethod = ` Operating method:

1. Define the reader outcome. Name the primary audience, their starting knowledge, the decision or action they must take, the consequences of misunderstanding, the delivery medium, and the useful lifetime of the document. Write a one-sentence outcome such as "an on-call engineer can restore service without guessing" or "an approver can choose an option with its cost and residual risk visible." If distinct audiences need incompatible depth or actions, create layered sections or separate artifacts rather than averaging them into one vague reader.

2. Establish source authority. Inventory specifications, code, runtime evidence, owner decisions, metrics, prior documents, and external references. Prefer primary and current sources. Record version and date where facts can drift. Label observed fact, cited fact, inference, recommendation, estimate, and unknown distinctly. Never invent sponsor approval, provider behavior, benchmark results, roadmap commitment, or certainty to make prose smoother. When sources conflict, expose the conflict and identify the authority needed to resolve it.

3. Choose a structure that matches use. Decision documents lead with outcome, options, recommendation, consequences, and ask. Instructions lead with prerequisites, safe starting state, ordered actions, decision points, expected feedback, recovery, and completion checks. References optimize stable lookup with names, types, defaults, constraints, errors, and examples. Technical explanations move from system boundary and flow to mechanisms, tradeoffs, and evidence. Status reports separate completed activity, demonstrated outcome, blockers, and next decisions.

4. Build an evidence-backed outline. Draft headings as questions the reader must answer. Under each heading, list the claim, its source, the necessary context, and the action it enables. Put safety warnings and prerequisites before the action they constrain. Put the decision or requested action where it cannot be buried. Remove sections that do not change understanding, action, or traceability. Use tables for exact comparisons and repeated fields, diagrams for ownership or flow, and lists for genuinely parallel items; do not use decoration as a substitute for hierarchy.

5. Preserve precision without forcing jargon. Define domain terms at first use and use one term for one concept. Include units, time windows, denominators, environment, sample size, and version scope with metrics. Distinguish absolute from relative changes and package size from runtime cost. Keep provider and product identities exact. Examples must be executable and tested, or explicitly labeled illustrative. Place normative requirements apart from commentary so readers can tell what is required.

6. Make decisions and authority explicit. State who owns the next action, what approval is required, when it is due, and what happens if no action occurs. Separate recommendation from authorization. A document, prompt, checklist, hidden control, or skill cannot grant permissions that the reader or system does not possess. For destructive, expensive, security-sensitive, or irreversible steps, specify the boundary, consequence, safer alternative, and recovery requirement before presenting the command or action.

7. Design for failure and uncertainty. Instructions must describe recognizable failure signals, likely causes only when evidence supports them, safe recovery steps, and escalation criteria. Plans and reports must expose dependencies, confidence, residual risk, and missing evidence. References must document errors, invalid states, compatibility, and deprecation. Avoid "simply," "just," and other wording that hides prerequisites. Never turn an unknown into a plausible default; tell the reader how to discover or supply the missing value.

8. Provide concrete state-aware examples. Show at least one representative success and, where consequential, one invalid, denied, interrupted, or recovery case. Example: do not write only "set the API key and retry." Explain where the supported credential belongs, how to confirm its scope without revealing it, the expected success signal, the unauthorized signal, and how to remove or rotate it. Keep examples consistent with the normative contract and repository conventions. Redact secrets and personal data without making the example misleading.

9. Validate the artifact mechanically and behaviorally. Check links, anchors, commands, code, schemas, terminology, units, numbering, version labels, accessibility, and rendering in the actual delivery medium. Then ask an independent reviewer or representative reader to make the intended decision, complete the task, or retrieve a specified fact using only the artifact. Observe hesitation, incorrect assumptions, and hidden prerequisite knowledge. Revise the source of confusion rather than adding a catch-all disclaimer at the end.

10. Guard against common misinterpretation. Put scope limits next to claims, not several sections later. Pair every abbreviation with a definition, every pronoun with an unambiguous referent, every option with consequences, and every status with its evidence date. Distinguish "not tested" from "failed," "deployed" from "enabled," "enabled" from "adopted," and "locally verified" from "released." Avoid universal language such as "always" or "secure" unless the evidence supports the full domain.

11. Plan maintenance. Name the source of truth, owner, review trigger, generated versus hand-authored portions, and deprecation path. Prefer references to authoritative definitions over copied values that will drift, while preserving enough context for the document to remain usable. If source changes invalidate the document, make that dependency visible. Remove or clearly mark stale alternatives so later agents do not follow two competing instructions.

12. Perform a final contradiction and action review. Compare summary against detail, tables against prose, examples against requirements, and recommendations against evidence. Confirm the reader can identify what changed, what is true now, what remains uncertain, what they must do, and how they know they succeeded. Example: "release complete" is misleading when only the build passed; report build identity, deployment state, activation state, observed product behavior, rollback readiness, and missing production evidence separately. Communication is not complete when polish hides weak evidence, essential context remains tribal knowledge, or the intended reader cannot act without asking the author to interpret it.`;

const planningNames = new Set([
  'planning',
  'architecture-planning',
  'migration-planning',
  'release-planning',
]);
const implementationNames = new Set([
  'implementation',
  'feature-implementation',
  'refactor-implementation',
  'integration-implementation',
]);
const debuggingNames = new Set([
  'debugging',
  'deterministic-debugging',
  'concurrency-debugging',
  'distributed-debugging',
  'performance-debugging',
  'hardware-runtime-debugging',
]);
const verificationNames = new Set([
  'verification',
  'functional-verification',
  'visual-verification',
  'accessibility-verification',
  'reliability-verification',
  'security-verification',
  'performance-verification',
]);

export const DELIVERY_SKILL_PLAYBOOKS = Object.fromEntries(
  Object.entries(CORE_DELIVERY_PLAYBOOKS).map(([name, playbook]) => [
    name,
    `${playbook}${planningNames.has(name) ? planningMethod : implementationNames.has(name) ? implementationMethod : debuggingNames.has(name) ? debuggingMethod : verificationNames.has(name) ? verificationMethod : communicationMethod}`,
  ]),
) as { [Name in keyof typeof CORE_DELIVERY_PLAYBOOKS]: string };

export type DeliverySkillPlaybookName = keyof typeof DELIVERY_SKILL_PLAYBOOKS;
