import type { ModelDef } from "@koryphaios/shared";

export const AnthropicModels: ModelDef[] = [
  // Current Models (as of March 2026)
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "anthropic",
    apiModelId: "claude-3-7-sonnet-20250219",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0.30,
    costPerMOutputCached: 3.75,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "anthropic",
    apiModelId: "claude-3-5-sonnet-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    costPerMInputCached: 0.30,
    costPerMOutputCached: 3.75,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "anthropic",
    apiModelId: "claude-3-5-haiku-20241022",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.80,
    costPerMOutputTokens: 4.0,
    costPerMInputCached: 0.08,
    costPerMOutputCached: 1.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "anthropic",
    apiModelId: "claude-3-opus-20240229",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 75.0,
    costPerMInputCached: 1.50,
    costPerMOutputCached: 18.75,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "anthropic",
    apiModelId: "claude-3-haiku-20240307",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.25,
    costPerMOutputTokens: 1.25,
    costPerMInputCached: 0.03,
    costPerMOutputCached: 0.31,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },

  // Legacy Models (older versions)
  {
    id: "claude-3-sonnet",
    name: "Claude 3 Sonnet (Legacy)",
    provider: "anthropic",
    apiModelId: "claude-3-sonnet-20240229",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    tier: "flagship",
  },
];
