import type { ModelDef } from "@koryphaios/shared";

export const AzureModels: ModelDef[] = [
  {
    id: "azure.gpt-4o",
    name: "Azure OpenAI – GPT-4o",
    provider: "azure",
    apiModelId: "gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 2.50,
    costPerMOutputTokens: 10.0,
    costPerMInputCached: 1.25,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "azure.gpt-4o-mini",
    name: "Azure OpenAI – GPT-4o mini",
    provider: "azure",
    apiModelId: "gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    costPerMInputCached: 0.075,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "azure.o1",
    name: "Azure OpenAI – o1",
    provider: "azure",
    apiModelId: "o1",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 60.0,
    costPerMInputCached: 7.50,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "azure.o1-mini",
    name: "Azure OpenAI – o1-mini",
    provider: "azure",
    apiModelId: "o1-mini",
    contextWindow: 128_000,
    maxOutputTokens: 65_536,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "azure.o3-mini",
    name: "Azure OpenAI – o3-mini",
    provider: "azure",
    apiModelId: "o3-mini",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  // Legacy GPT-4 models
  {
    id: "azure.gpt-4",
    name: "Azure OpenAI – GPT-4 (Legacy)",
    provider: "azure",
    apiModelId: "gpt-4",
    contextWindow: 8_192,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 30.0,
    costPerMOutputTokens: 60.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "azure.gpt-4-turbo",
    name: "Azure OpenAI – GPT-4 Turbo (Legacy)",
    provider: "azure",
    apiModelId: "gpt-4-turbo",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 10.0,
    costPerMOutputTokens: 30.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
];
