import type { ModelDef } from "@koryphaios/shared";

export const OpenAIModels: ModelDef[] = [
  // Current Models (as of March 2026)
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    apiModelId: "gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 2.50,
    costPerMOutputTokens: 10.0,
    costPerMInputCached: 1.25,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "openai",
    apiModelId: "gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    costPerMInputCached: 0.075,
    costPerMOutputCached: 0.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "o1",
    name: "o1",
    provider: "openai",
    apiModelId: "o1",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 60.0,
    costPerMInputCached: 7.50,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "o1-mini",
    name: "o1-mini",
    provider: "openai",
    apiModelId: "o1-mini",
    contextWindow: 128_000,
    maxOutputTokens: 65_536,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    provider: "openai",
    apiModelId: "o3-mini",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    costPerMInputTokens: 1.10,
    costPerMOutputTokens: 4.40,
    costPerMInputCached: 0.55,
    costPerMOutputCached: 0.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "reasoning",
  },

  // Legacy Models
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo (Legacy)",
    provider: "openai",
    apiModelId: "gpt-4-turbo",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 10.0,
    costPerMOutputTokens: 30.0,
    tier: "flagship",
  },
  {
    id: "gpt-4",
    name: "GPT-4 (Legacy)",
    provider: "openai",
    apiModelId: "gpt-4",
    contextWindow: 8_192,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 30.0,
    costPerMOutputTokens: 60.0,
    tier: "flagship",
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5 Turbo (Legacy)",
    provider: "openai",
    apiModelId: "gpt-3.5-turbo",
    contextWindow: 16_384,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 0.50,
    costPerMOutputTokens: 1.50,
    tier: "fast",
  },
];
