import type { ModelDef } from "@koryphaios/shared";

export const OpenRouterModels: ModelDef[] = [
  {
    id: "openrouter.gpt-4o",
    name: "OpenRouter – GPT-4o",
    provider: "openrouter",
    apiModelId: "openai/gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 2.50,
    costPerMOutputTokens: 10.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gpt-4o-mini",
    name: "OpenRouter – GPT-4o mini",
    provider: "openrouter",
    apiModelId: "openai/gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "openrouter.claude-3.7-sonnet",
    name: "OpenRouter – Claude 3.7 Sonnet",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3.7-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.claude-3.5-sonnet",
    name: "OpenRouter – Claude 3.5 Sonnet",
    provider: "openrouter",
    apiModelId: "anthropic/claude-3.5-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gemini-2.0-pro",
    name: "OpenRouter – Gemini 2.0 Pro",
    provider: "openrouter",
    apiModelId: "google/gemini-2.0-pro-exp",
    contextWindow: 2_000_000,
    maxOutputTokens: 8_192,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "openrouter.gemini-2.0-flash",
    name: "OpenRouter – Gemini 2.0 Flash",
    provider: "openrouter",
    apiModelId: "google/gemini-2.0-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    tier: "fast",
  },
  
  // Legacy
  {
    id: "openrouter.gpt-3.5-turbo",
    name: "OpenRouter – GPT-3.5 Turbo (Legacy)",
    provider: "openrouter",
    apiModelId: "openai/gpt-3.5-turbo",
    contextWindow: 16_384,
    maxOutputTokens: 4_096,
    tier: "fast",
  },
];
