import type { ModelDef } from "@koryphaios/shared";

/**
 * OpenCode Zen — curated models at opencode.ai/zen (API key from opencode.ai/auth).
 * Full model list from https://opencode.ai/zen/v1/models
 * Additional models are discovered via GET /v1/models when the provider is configured.
 */
export const OpenCodeZenModels: ModelDef[] = [
  // Claude models (Anthropic) - uses /v1/messages endpoint
  {
    id: "opencodezen.claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet (Zen)",
    provider: "opencodezen",
    apiModelId: "claude-3-7-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 50_000,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: true,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "opencodezen.claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet (Zen)",
    provider: "opencodezen",
    apiModelId: "claude-3-5-sonnet",
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 3.0,
    costPerMOutputTokens: 15.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "opencodezen.claude-3-5-haiku",
    name: "Claude 3.5 Haiku (Zen)",
    provider: "opencodezen",
    apiModelId: "claude-3-5-haiku",
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.8,
    costPerMOutputTokens: 4.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "opencodezen.claude-3-opus",
    name: "Claude 3 Opus (Zen)",
    provider: "opencodezen",
    apiModelId: "claude-3-opus",
    contextWindow: 200_000,
    maxOutputTokens: 4_096,
    costPerMInputTokens: 15.0,
    costPerMOutputTokens: 75.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  // Gemini models (Google) - uses /v1/models/gemini-* endpoints
  {
    id: "opencodezen.gemini-2-0-pro",
    name: "Gemini 2.0 Pro (Zen)",
    provider: "opencodezen",
    apiModelId: "gemini-2.0-pro",
    contextWindow: 2_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "opencodezen.gemini-2-0-flash",
    name: "Gemini 2.0 Flash (Zen)",
    provider: "opencodezen",
    apiModelId: "gemini-2.0-flash",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  // GPT models (OpenAI) - uses /v1/chat/completions endpoint
  {
    id: "opencodezen.gpt-4o",
    name: "GPT-4o (Zen)",
    provider: "opencodezen",
    apiModelId: "gpt-4o",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 2.50,
    costPerMOutputTokens: 10.0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "opencodezen.gpt-4o-mini",
    name: "GPT-4o mini (Zen)",
    provider: "opencodezen",
    apiModelId: "gpt-4o-mini",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPerMInputTokens: 0.15,
    costPerMOutputTokens: 0.60,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  // GLM models - uses /v1/chat/completions endpoint
  {
    id: "opencodezen.glm-4",
    name: "GLM-4 (Zen)",
    provider: "opencodezen",
    apiModelId: "glm-4",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.6,
    costPerMOutputTokens: 2.2,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  // MiniMax models - uses /v1/chat/completions endpoint
  {
    id: "opencodezen.minimax-text-01",
    name: "MiniMax Text 01 (Zen)",
    provider: "opencodezen",
    apiModelId: "minimax-text-01",
    contextWindow: 1_000_000,
    maxOutputTokens: 32_000,
    costPerMInputTokens: 0.3,
    costPerMOutputTokens: 1.2,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
  },
  // Kimi models - uses /v1/chat/completions endpoint
  {
    id: "opencodezen.kimi-k1-5",
    name: "Kimi K1.5 (Zen)",
    provider: "opencodezen",
    apiModelId: "kimi-k1.5",
    contextWindow: 256_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.6,
    costPerMOutputTokens: 3.0,
    canReason: true,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "flagship",
  },
  // Default/fallback model
  {
    id: "opencodezen.default",
    name: "OpenCode Zen (auto)",
    provider: "opencodezen",
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    canReason: false,
    supportsAttachments: false,
    supportsStreaming: true,
    tier: "fast",
    isGeneric: true,
  },
];
