import type { ModelDef } from "@koryphaios/shared";

/**
 * Curated Vertex AI model list (fallback). Vertex uses GCP auth and a different API;
 * this list is kept in sync with Vertex AI docs. For dynamic discovery, a future
 * integration could call Vertex AI's list models endpoint.
 */
export const VertexAIModels: ModelDef[] = [
  {
    id: "vertexai.gemini-2.0-flash",
    name: "VertexAI – Gemini 2.0 Flash",
    provider: "vertexai",
    apiModelId: "gemini-2.0-flash-001",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.075,
    costPerMOutputTokens: 0.30,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "vertexai.gemini-2.0-pro",
    name: "VertexAI – Gemini 2.0 Pro",
    provider: "vertexai",
    apiModelId: "gemini-2.0-pro-exp-02-05",
    contextWindow: 2_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0,
    costPerMOutputTokens: 0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
  {
    id: "vertexai.gemini-1.5-flash",
    name: "VertexAI – Gemini 1.5 Flash",
    provider: "vertexai",
    apiModelId: "gemini-1.5-flash-001",
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 0.075,
    costPerMOutputTokens: 0.30,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "fast",
  },
  {
    id: "vertexai.gemini-1.5-pro",
    name: "VertexAI – Gemini 1.5 Pro",
    provider: "vertexai",
    apiModelId: "gemini-1.5-pro-001",
    contextWindow: 2_000_000,
    maxOutputTokens: 8_192,
    costPerMInputTokens: 1.25,
    costPerMOutputTokens: 5.0,
    costPerMInputCached: 0,
    costPerMOutputCached: 0,
    canReason: false,
    supportsAttachments: true,
    supportsStreaming: true,
    tier: "flagship",
  },
];
